NEXT-13575 fix: keep inheritance of language chain during seo url update
shopware/platform pull request #1646
Opened 2021-02-12 16:48 UTC by bnussbau

### 1. Why is this change necessary?
language inheritance is broken when generating seo urls .
example: german (austria) extends german (germany).
current code falls back to system default language.

### 2. What does this change do, exactly?
fixes wrong uuid comparison

### 3. Describe each step to reproduce the issue or behaviour.
run dal:index:refresh

language interitance is broken when generating seo urls 
example: german (austria) extends german (germany).
current code falls back to system default language.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-02-17 10:37 UTC, philipgatzka requested changes
Hi @bnussbau , thank you for creating this pull request. Please implement a regression test covering this problem, so we can be sure that the issue won't come up again in the future 🙂

2021-02-17 10:37 UTC, philipgatzka commented on changelog/_unreleased/2021-02-03-keep-inheritance-of-language-chain-during-seo-url-update.md
> +___
This line is superfluous

2021-03-03 07:26 UTC, bneumann97 commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2021-03-03 07:26 UTC, closed without merging

2021-03-16 15:32 UTC, bnussbau commented
I happily accept suggestions on how to write a useful test for this specific case. This PR should not be just declined and closed, this is an issue with great impact and a very simple fix.

Similar to this PR: https://github.com/shopware/platform/pull/1647, which was merged without test

2021-04-23 13:15 UTC, philipgatzka commented
Hi @bnussbau , please excuse my late response. Off the top of my head there are two ways to make sure the comparison is done right. One could either implement an integration test and actually execute the `update()` method, checking the result afterwards or mock the `Connection` and make sure its `executeQuery` method is called with the correct query (-parameters) at least once. In case you're up to work on this, please feel free to create another pull request 🙂