NTR: Fix ConfigSet on CLI for bool values
shopware/platform pull request #1722
Opened 2021-03-18 14:51 UTC by boxblinkracer

### 1. Why is this change necessary?
i found out that setting of a bool value FALSE does not work with the CLI
because for me all values are interpreted as a string type and thus are always true.
therefore setting of FALSE does never work

### 2. Describe each step to reproduce the issue or behaviour.
create a plugin with a bool config (like testMode TRUE/FALSE)
and try to set both on CLI
only true works, false does not

PLEASE VERIFY if its also the case for you,
if so and if you are happy with the request, I'd be happy about a merge

2021-03-18 18:46 UTC, mitelg commented
imo this should be fixed in the command and not in the service. 
so the caller of the service needs to ensure, that the right value is written into the config. 
other callers of the service might still want to write the strings "true" and "false" into the config 😉

2021-03-19 13:31 UTC, boxblinkracer commented
hi
oh yeah, no problem, makes sense if its modelled like that

ill do it when i have some spare time, :)

2021-03-19 14:13 UTC, philipgatzka requested changes
Hi @boxblinkracer , thank you for tackling this issue 😄 I'm with Michael here, since this problem only occurs when using the shell interface, where types can't be determined. Maybe this could also be solved with an additional flag for the command, which would let users choose the intended type/behaviour (`--bool`, `--toggle`, ...)?

2021-03-19 15:09 UTC, boxblinkracer commented
hi

we do lots of CI automation, and i actually discovered it when developing a plugin and preparing it for SANDBOX mode true/false....

i dont think one would really think of that additional param...so what would be is that someone writes "xyz false" and its accidentally true...no one would think there has to be an optional parameter

however i thought about if its a good idea to use "true" "false" and thus avoid it from being really used as "string".
...i could not think of a situation where you would want true/false as string value, so i think it might be ok to convert it.

also, it might be an idea to auto-convert these to bool, and do an optional parameter if you want to stick with strings for rare scenarios

but in the end...could you tell me what you want? then i would take some time and do it, to hopefully get that in an upcoming version

2021-03-22 11:05 UTC, philipgatzka commented
Alright, I see. So I've discussed this with a few colleagues - our preferred way of handling this would be an additional required parameter for the command actually, so it can't be forgotten.

Since this would break existing integrations with CI systems or other programs in general, the behaviour should only be enabled with the next major version, v6.5.0.0.

So our proposal would be the following:
- `system:config:set {key} {value} [type]` - type is optional, this way of executing the command should be marked as deprecated but the parameter is respected if given (otherwise the current behaviour is used)
- `system:config:set {key} {value} {type}` - type is mandatory, default from >= v6.5.0.0

2021-04-07 09:41 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2021-04-07 09:41 UTC, closed without merging