Improve CustomerValidationFactory
shopware/platform pull request #1738
Opened 2021-03-24 14:14 UTC by bpesch

### 1. Why is this change necessary?
It improves the codes performance and readability.

### 2. What does this change do, exactly?
* Changes order of method calls
* Replaces merge process with less bloated and more performant approach

### 3. Describe each step to reproduce the issue or behaviour.
-

### 4. Please link to the relevant issues (if any).
-

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2021-03-25 10:42 UTC, philipgatzka requested changes
Hi @bpesch , thank you for creating this pull request 🙂 Please add a test for your change, so we can be sure this issue won't come up again, and the code works as intended.

2021-03-25 10:43 UTC, philipgatzka requested changes

2021-03-25 10:43 UTC, philipgatzka commented on changelog/_unreleased/2021-03-24-improve-customer-validation-factory.md
> +* Improved ````CustomerValidationFactory::update```` performance
```suggestion
* Changed `CustomerValidationFactory::update` to improve performance
```

2021-03-25 10:43 UTC, philipgatzka commented on changelog/_unreleased/2021-03-24-improve-customer-validation-factory.md
> +* Improved ````CustomerValidationFactory::update```` performance
Please change the other line accordingly

2021-03-25 18:08 UTC, bpesch commented
Hi @philipgatzka,
the `CustomerValidationFactory` does not seem to have tests written for the `update` and `create` methods yet.
Besides that, those improvements are performance improvements and should not change the codes functionality at all.
Best regards!

2021-04-23 13:02 UTC, philipgatzka requested changes
Hi @bpesch , you're right, the change should not cause a difference in the output, but we'd like to make sure that doesn't happen (currently as well as in future commits). You don't need to implement a test case for the whole class, but only one making sure the `$definition` returned by `create()` is altered as expected. If you need any assistance implementing this with PHPUnit, please feel free to ask 🙂

2021-05-06 23:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=1738) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=1738) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: bpesch<br/>:x: Ben Pesch<br/><hr/>**Ben Pesch** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1738) it.</sub>

2021-05-06 23:56 UTC, bpesch commented
Hi @philipgatzka,
I didn't have a lot of time in the past weeks. Sorry for my late answer.
Please let me know if the added test case is sufficient!

2021-05-07 06:43 UTC, philipgatzka approved these changes
Hi @bpesch , no worries! Thank you for adding the test. Looks great 🙂

2021-05-07 07:03 UTC, bpesch commented
Should I add the ticket id to the changelog file?

2021-05-07 07:11 UTC, philipgatzka commented
No, it's fine. Since we're creating the ticket in the process, we usually add another commit on top to add the issue key.

2021-06-01 12:09 UTC, closed without merging

2021-06-01 12:09 UTC, philipgatzka commented
Thank you for your contribution @bpesch! 🚀