feat: Reformat output of system:config:get
shopware/platform pull request #1756
Opened 2021-03-30 17:48 UTC by aragon999

### 1. Why is this change necessary?
I just discovered the command `system:config:get` but I find its usage very difficult if you fetch several entries, so it is now formatted such that the config key is visible.

### 2. What does this change do, exactly?
Reformat output of system:config:get

### 3. Describe each step to reproduce the issue or behaviour.
`php bin/console system:config:get core`

### 4. Please link to the relevant issues (if any).
-

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-03-31 12:47 UTC, philipgatzka requested changes
Hi @aragon999 , I quickly checked out your branch and had a look at the command output. It works great for objects/arrays, which weren't readable at all before:
```shell
bin/console system:config:get 'core.scheduled_indexers'
1
1
1
# ...
```
```shell
bin/console system:config:get 'core.scheduled_indexers'
product.indexer => 1
Swag.TreeIndexer => 1
Swag.EntityIndexer => 1
# ...
```
One thing I've noticed though, is that not only the output for the unreadable objects has changed now, but also for any other type:
```shell
bin/console system:config:get 'core.logging.entryLifetimeSeconds'
2678400
```
```shell
bin/console system:config:get 'core.logging.entryLifetimeSeconds'
core.logging.entryLifetimeSeconds => 2678400
```
I could imagine this would be problematic in case one has been reusing the output in a script or some other integration until now.

I asked a few colleagues about this and we think this new behaviour should rather be disabled by default (for now) and enabled through providing a flag like `--pretty`, `--human-readable`, or similar. Would you mind implementing your change in this way?

2021-03-31 13:25 UTC, aragon999 commented
So when adding the option e.g. `--pretty`, I would think that the objects should also be output as some machine readable format. For example JSON. Which would be conflicting, since we cannot break backwards compatibility for scalar values.
Or one would have two different output formats. Where you should now what is returned. 
Any suggestion?

In general I would suggest that the option `--pretty` is enabled by default at some point and one needs to explicitly disable it, if not needed (sensible defaults).

2021-04-13 09:43 UTC, philipreinken commented
Hi @aragon999 , 

> So when adding the option e.g. --pretty, I would think that the objects should also be output as some machine readable format. For example JSON.

JSON sounds great 👍🏼  Implementing this could also be simpler than another solution I guess, since the config values are JSON-Fields already.

> In general I would suggest that the option --pretty is enabled by default at some point and one needs to explicitly disable it, if not needed (sensible defaults).

I agree, that point in time should be the next major then.

So to summarize, do you think we can agree on this?
 - The current (and inconsistent) behaviour stays in place so we don't break any existing integrations
 - JSON-Output may be enabled via a flag
 - With the next major (presumably v6.5.0.0) this switches around, so the JSON-Output will be the default and the old behaviour may be used via a flag

2021-04-27 09:46 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2021-04-27 09:46 UTC, closed without merging