Remove the word honeypot from its div class to remove ability for bot…
shopware/platform pull request #1761
Opened 2021-04-06 08:10 UTC by juripetersen

…s to ignore this field

### 1. Why is this change necessary?
The word honeypot is existant as a class for the wrapper div in ```honeypot.html.twig```. 
Bots or scrapers use labels and classes to identify honeypots and we had occurences where the Shopware Honeypot does not work because it is ignored.

### 2. What does this change do, exactly?
Change the class of div in ```honeypot.html.twig``` from ```captcha--honeypot``` to ```register-shopware-surname```

### 3. Describe each step to reproduce the issue or behaviour.
Hard to reproduce because you will need a bot that registers accounts and uses a mechanism to identify honeypots by labels and classes.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-14628
https://github.com/shopware/platform/issues/1760

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2021-04-06 08:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=1761) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=1761) before we can accept your contribution.<br/><hr/>**vvjpet** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1761) it.</sub>

2021-04-06 11:26 UTC, philipgatzka requested changes
Hi @juripetersen , thank you for putting in the time to create this pull request 🙂 I only have a few minor suggestions, please have a look.

2021-04-06 11:26 UTC, philipgatzka commented on changelog/_unreleased/2021-04-06-honeypots-remove-label.md
> +* Changed class from ```div class="captcha--honeypot"``` to ```div class="register-shopware-surname"``` to remove the appearance of the word honeypot
```suggestion
* Changed class from `div class="captcha--honeypot"` to `div class="register-shopware-surname"` to remove the appearance of the word honeypot
```

2021-04-06 11:26 UTC, philipgatzka commented on src/Storefront/Resources/views/storefront/component/captcha/honeypot.html.twig
> +    <div class="register-shopware-surname">
This is almost the content of the constant which is already used below for the inputs name - would you mind using it here as well? Something along the line of `constant('[...]::CAPTCHA_REQUEST_PARAMETER')|replace({'_': '-'})` should work I think.

2021-04-07 11:41 UTC, juripetersen commented
I modified my pull request to include the suggestions you made!

2021-04-07 12:29 UTC, philipgatzka approved these changes

2021-04-08 07:21 UTC, closed without merging

2021-04-08 07:22 UTC, philipgatzka commented
Thank you for contributing @juripetersen ! 🥳