Add datetime-local and time-local to system-config
shopware/platform pull request #1763
Opened 2021-04-07 08:54 UTC by maximilianruesch

### 1. Why is this change necessary?
The localized datetime field `datetime-local` was added in the commit ce3d73d99c061c77420c9183dbe289b545871e89 . This field type is not available in SystemConfig and the respective `sw-form-field-renderer` in the administration.
A new time-local field was also missing in the commit.

### 2. What does this change do, exactly?
It adds the `datetime-local` and `time-local` types to the SystemConfig and the `sw-form-field-renderer` and the `time-local` logic to the `sw-datepicker` component.

Below is a view of the changes in the administration and the respective values database:
![image](https://user-images.githubusercontent.com/78490564/113838859-7b51ad80-978f-11eb-9125-4b337aaaf7b2.png)
![image](https://user-images.githubusercontent.com/78490564/113838898-83115200-978f-11eb-899c-e20c4c3028b0.png)

### 3. Describe each step to reproduce the issue or behaviour.
1. In a plugin config file of choice, create an `input-field` with type `datetime-local` or `time-local`
2. Log in administration and go to the config of the selected plugin
3. Shopware will show an error notification saying that the `datetime-local` (or `time-local`) type is not registered

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-04-07 08:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=1763) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=1763) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1763) it.</sub>

2021-04-07 12:24 UTC, J-Rahe commented
Hey @maximilianruesch, could you please complete the [changelog](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md)?

2021-04-08 12:02 UTC, jleifeld requested changes
Thanks for your contribution! :)

Wouldn´t it be better if we only provide one timeField and one dateTimeField? This fields show only the local time. The saved value in the database should still be UTC.

So if I open my administration in a timezone of +2 I see the time which I have local. But when I save the value it would be saved as a UTC value.

Then it is consistent through the whole administration because since 6.4 we will show the local time and save it in UTC to the database.

2021-04-08 12:16 UTC, maximilianruesch commented
Just to clarify:

Is your suggested change to reverse the `datetime-local` changes made by your devs and instead change the existing `time` and  `datetime` fields to display local times and save UTC?

If not, afaik the `datetime-local` field handling still exists in the datepicker component in the 6.4 RC (see: https://github.com/shopware/platform/blob/v6.4.0.0-RC1/src/Administration/Resources/app/administration/src/app/component/form/sw-datepicker/index.js).
It seems that the normal `datetime` and `time` fields are still operation as normal...

2021-04-09 13:33 UTC, jleifeld commented
I will discuss this on monday with a colleague who creates the changes. Then we can give you an answer :)

2021-04-12 14:13 UTC, jleifeld commented
We think that your solution is fine 👍  The preferred way is to use local time but when the user cares about the UTC time he can use this field.

2021-04-13 07:15 UTC, J-Rahe commented
Hey @maximilianruesch, now that that is clarified, would you please still complete the [changelog](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) (author and author_email)?

2021-04-13 07:16 UTC, maximilianruesch commented
I was just discussing this with a coworker, i am on it :)

2021-04-13 07:58 UTC, jleifeld commented
Short info additionally:

It would still be good if the user can directly see in which time zone he is editing the times/data. We will evaluate a concept for this and designing a good solution how to implement this visually. We will inform you back as soon as the topic is finished.

2021-04-19 09:25 UTC, fixpunkt commented
> Short info additionally:
> 
> It would still be good if the user can directly see in which time zone he is editing the times/data. We will evaluate a concept for this and designing a good solution how to implement this visually. We will inform you back as soon as the topic is finished.

As an insipiration, this is how GitHub solves this in https://github.com/settings/reminders/shopware:

![image](https://user-images.githubusercontent.com/2817302/115213477-d70e2600-a101-11eb-8169-f8a87e9efb50.png)

2021-06-25 09:32 UTC, jleifeld commented
Together with Pickware we have thought out a universal solution, which will be implemented in the future and therefore this PR can be closed.

2021-06-25 09:32 UTC, closed without merging