Fix error when decorating ProductPriceCalculator
shopware/platform pull request #1908
Opened 2021-06-10 14:48 UTC by darinda

fixes #1907

### 1. Why is this change necessary?
It fixes the bug #1907

### 2. What does this change do, exactly?
Update the type of the `$priceCalculator` in the `ProductCartProcessor` class as described in #1907

### 3. Describe each step to reproduce the issue or behaviour.
Decorate the PriceCalculator as described [in the official documentation](https://developer.shopware.com/docs/guides/plugins/plugins/checkout/cart/customize-price-calculation#decorating-the-calculator)

### 4. Please link to the relevant issues (if any).
#1907

### 5. Checklist

- [- ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [-] I have written or adjusted the documentation according to my changes
- [-] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-06-10 14:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=1908) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=1908) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1908) it.</sub>

2021-06-11 08:32 UTC, J-Rahe requested changes
Hey @kleinmann, thanks for opening the PR : )
I have made a few comments to your changelog file, could you please have a look at them?

2021-06-11 08:32 UTC, J-Rahe commented on changelog/_unreleased/2021-06-10-fix-error-when-decorating-price-calculator.md
> +issue: <tbd>
You are [missing your name and email](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md), please add them.

2021-06-11 08:32 UTC, J-Rahe commented on changelog/_unreleased/2021-06-10-fix-error-when-decorating-price-calculator.md
> +* Updated the type of the `$priceCalculator` argument in the `ProductCartProcessor` class to
Please use an [Keyword](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md).

2021-06-11 08:51 UTC, kleinmann commented
> Hey @kleinmann, thanks for opening the PR : )
> I have made a few comments to your changelog file, could you please have a look at them?

Thank you for including me, not my PR though 😄

2021-06-11 09:12 UTC, J-Rahe commented
@kleinmann, sorry,  must have selected you accidentally and not checked it :  /.

2021-06-15 14:36 UTC, closed without merging

2021-06-17 09:16 UTC, mitelg commented
thanks for your contribution @darinda   👍🎉💙