dispatch merged event only if a merge actually has been done
shopware/platform pull request #1928
Opened 2021-06-19 14:18 UTC by Guite

### 1. Why is this change necessary?
Every time a guest has put some product into the cart and logs in later he receives the flash message "checkout.cart-merged-hint" caused by `Shopware\Storefront\Event\CartMergedSubscriber`, saying that the cart might potentially also contain products from earlier sessions.
While the whole merge process in `Shopware\Core\System\SalesChannel\Context\SalesChannelContextRestorer#mergeCart` is only processed if `$guestCart->getLineItems()->count() > 0` it does not consider the amount of line items in `$customerCart`.

### 2. What does this change do, exactly?
Since I didn't want to change the behavior of when the merge function and when the recalculate method are called, I decided to check the amount of line items in `$customerCart` before the guest cart's items are merged into it.
After the merge is done the `CartMergedEvent` is now only dispatched if customer's cart already contained some products before the guest cart has been merged.

### 3. Describe each step to reproduce the issue or behaviour.
1. Log in with your account.
2. Ensure your customer's cart does _not_ contain any products.
3. Log out.
4. Put some products into your guest's cart.
5. Log in again
6. See the confusing flash message about earlier products.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2021-06-22 09:08 UTC, J-Rahe requested changes
Hey @Guite, please update your changelog.

2021-06-22 09:08 UTC, J-Rahe commented on changelog/_unreleased/2021-06-19-suppress-confusing-cart-merge-flash-message-after-login-when-not-appropriate.md
> +* Inside `Shopware\Core\System\SalesChannel\Context\SalesChannelContextRestorer#mergeCart` there is now a check if the amount of customer cart items was greater than zero before the guest's cart is m
Please use the [keywords](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) here.

2021-06-22 09:08 UTC, J-Rahe commented on changelog/_unreleased/2021-06-19-suppress-confusing-cart-merge-flash-message-after-login-when-not-appropriate.md
> +* Inside `Shopware\Core\System\SalesChannel\Context\SalesChannelContextRestorer#mergeCart` there is now a check if the amount of customer cart items was greater than zero before the guest's cart is m
e.g. "Changed trigger logic for `CartMergedEvent`.The `CartMergedEvent` event is now only thrown if a merge of a previous shopping cart has really taken place."

2021-06-22 09:23 UTC, Guite commented on changelog/_unreleased/2021-06-19-suppress-confusing-cart-merge-flash-message-after-login-when-not-appropriate.md
> +* Inside `Shopware\Core\System\SalesChannel\Context\SalesChannelContextRestorer#mergeCart` there is now a check if the amount of customer cart items was greater than zero before the guest's cart is m
@J-Rahe changed like you requested

2021-08-25 07:13 UTC, closed without merging

2021-08-30 13:13 UTC, NiklasLimberg commented
Hi,
thanks for your contrubution.