fix es criteria parser
shopware/platform pull request #1974
Opened 2021-07-25 21:24 UTC by pascaljosephy

### 1. Why is this change necessary?

This PR fixes two issues related to the Elasticsearch DAL:

* https://issues.shopware.com/issues/NEXT-16385
* https://issues.shopware.com/issues/NEXT-15038

### 2. What does this change do, exactly?

There are three things changed:

To fix https://issues.shopware.com/issues/NEXT-15038:

There was a general issue in how aggregations were translated to Elasticsearch DSL aggregations. If the field of an aggregation was a nested field, the whole aggregation was wrapped in a nested block: 

```
          "options-filtered": {
            "nested": {
                "path": "options"
            },
            "aggregations": {
                "options-filtered": {
                    "filter": {
                        "terms": {
                            "manufacturerId": [
                                "4f81ed4a0f3e4e99a57778aeab40d622"
                            ]
                        }
                    },
                    "aggregations": {
                        "options": {
                            "terms": {
                                "field": "options.id",
                                "size": 10000
                            }
                        }
                    }
                }
            }
        }
```

However, as the filter in the inner aggregation can be on a property in a different path, this can not be generally done with filter aggregations. Therefore, we changed the implementation of `parseAggregation` to make an exception for `FilterAggregation` and instead consider the nesting in the method `parseFilterAggregation`. Using this change, the above DAL query translates now correctly to:

```
          "options-filtered": {
            "filter": {
                "terms": {
                    "manufacturerId": [
                        "4f81ed4a0f3e4e99a57778aeab40d622"
                    ]
                }
            },
            "aggregations": {
                "options": {
                    "nested": {
                        "path": "options"
                    },
                    "aggregations": {
                        "options": {
                            "terms": {
                                "field": "options.id",
                                "size": 10000
                            }
                        }
                    }
                }
            }
        }
```

To fix https://issues.shopware.com/issues/NEXT-16385:

The property whitelist is implemented in the `ProductListingFeaturesSubscriber` (https://github.com/shopware/platform/blob/trunk/src/Core/Content/Product/SalesChannel/Listing/ProductListingFeaturesSubscriber.php#L505) and uses the aggregation `product.properties.groupId`. We therefore extend the product definition in Elasticsearch to also store the groupId of properties and options. 

Furthermore, there was another error using `FilterAggregation` in the DAL. If the filter query used a nested property, the resulting Elasticsearch DSL looked like this:

```
        "properties-filter": {
            "nested": {
                "path": "properties"
            },
            "aggregations": {
                "properties-filter": {
                    "filter": {
                        "terms": {
                            "properties.groupId": [
                                "a7b61971d67a474eb2bc281f9e4d5ee2"
                            ]
                        }
                    },
                    "aggregations": {
                        "properties": {
                            "terms": {
                                "field": "properties.id",
                                "size": 10000
                            }
                        }
                    }
                }
            }
        },
```

The filter query contains a nested property, which for some reason is removed from the Elasticsearch DSL in the method `parseFilterAggregation` (https://github.com/shopware/platform/blob/6366e824106d4a5ec080a3ca7a1119b0beaa8cc7/src/Elasticsearch/Framework/DataAbstractionLayer/CriteriaParser.php#L185). As nested queries are now handled directly inside the aggregation of the `FilterAggregation`, the nested query should be used directly. This leads to the correct DSL:

```
        "properties-filter": {
            "filter": {
                "nested": {
                    "path": "properties",
                    "query": {
                        "terms": {
                            "properties.groupId": [
                                "a7b61971d67a474eb2bc281f9e4d5ee2"
                            ]
                        }
                    }
                }
            },
            "aggregations": {
                "properties": {
                    "nested": {
                        "path": "properties"
                    },
                    "aggregations": {
                        "properties": {
                            "terms": {
                                "field": "properties.id",
                                "size": 10000
                            }
                        }
                    }
                }
            }
        },
```

General remark: We just fixed the two linked issues - it might be that there are other / new issues with these fixes. It would be an idea to add some formal tests to the criteria parser to ensure it's correctness also for future scenarios.

### 3. Describe each step to reproduce the issue or behaviour.

See the related issues for steps to reproduce.

### 4. Please link to the relevant issues (if any).

* https://issues.shopware.com/issues/NEXT-16385
* https://issues.shopware.com/issues/NEXT-15038

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-07-25 21:40 UTC, shyim commented
Can you add tests for your changes?

2021-07-26 06:09 UTC, pascaljosephy commented
@shyim Yes, I will add tests for the two issues as soon as I have time. I decided to already submit the PR so that code review can take place already :-)

2021-07-26 06:43 UTC, shyim requested changes

2021-07-26 06:43 UTC, shyim commented on src/Elasticsearch/Product/ElasticsearchProductDefinition.php
> +        $sql = "SELECT id, property_group_id FROM property_group_option WHERE id in (?)";
```suggestion
        $sql = "SELECT LOWER(HEX(id)), LOWER(HEX(property_group_id)) FROM property_group_option WHERE id in (?)";
```

2021-07-26 06:43 UTC, shyim commented on src/Elasticsearch/Product/ElasticsearchProductDefinition.php
> +        $data = $this->connection->fetchAll($sql, [Uuid::fromHexToBytesList($propertyIds)], [Connection::PARAM_STR_ARRAY]);
```suggestion
        $data = $this->connection->fetchAllKeyValue($sql, [Uuid::fromHexToBytesList($propertyIds)], [Connection::PARAM_STR_ARRAY]);
```

2021-07-26 06:43 UTC, shyim commented on src/Elasticsearch/Product/ElasticsearchProductDefinition.php
> +    private function fetchPropertyGroups($propertyIds = array()): array
```suggestion
    private function fetchPropertyGroups(array $propertyIds): array
```

2021-07-26 06:43 UTC, shyim commented on src/Elasticsearch/Product/ElasticsearchProductDefinition.php
> +
You can remove that lines then

2021-07-26 06:43 UTC, shyim commented on src/Elasticsearch/Product/ElasticsearchProductDefinition.php
> +        $propertyGroups = $this->fetchPropertyGroups(array_unique(array_merge(...array_map(fn ($item) => array_merge(json_decode($item['propertyIds'] ?? '[]', true), json_decode($item['optionIds'] ??
This variable looks like unused

2021-07-26 06:43 UTC, shyim commented on src/Elasticsearch/Framework/DataAbstractionLayer/CriteriaParser.php
> +            $this->parseAggregation($nested, $definition, $context)
Did you test it with a nested aggregation?

2021-07-26 06:43 UTC, shyim commented on changelog/_unreleased/2021-07-25-fix-es-criteria-parser.md
> +flag:
you need an title here and remove flag

2021-07-26 06:43 UTC, shyim commented on changelog/_unreleased/2021-07-25-fix-es-criteria-parser.md
> +# Elasticsearch
Replace it with Core

2021-07-26 10:51 UTC, pascaljosephy commented
Thanks @shyim for your feedback, I already implemented the suggestions. The test cases are coming as soon as I find the time.

2021-08-04 07:51 UTC, NiklasLimberg commented
Hi @pascaljosephy,
@OliverSkroblin took over this PR, because he has a ticket in the sprint which basically fixes the same thing. He'll probably merge your commit and add a few tests in a separate commit. So consider your PR merged

2021-08-04 07:52 UTC, NiklasLimberg commented
I'll close this PR once it is merged

2021-08-14 08:36 UTC, OliverSkroblin commented
Hi @pascaljosephy,

thanks for the cooperation. Liked discussed i changed the code a little bit to solve different parsing cases. 
The final changes are merged with this commit: https://github.com/shopware/platform/commit/9ce3e15bacab1651d5ace08d095dc27f3d73c236

2021-08-14 08:36 UTC, closed without merging