fix: select current date if the day of birth empty
shopware/platform pull request #2005
Opened 2021-08-05 14:46 UTC by stephan4p

### 1. Why is this change necessary?
If we leave the day of birth empty during registration he select the current date as day of birth in the account profile

### 2. What does this change do, exactly?
Query whether birthday is filled. Only then the variables for the select are generated.

### 3. Describe each step to reproduce the issue or behaviour.
- Register an user account and leave the birthday blank
- Look at account Profile and the the current day selected

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-08-05 18:00 UTC, shyim requested changes
You need to sign also the CLA :)

2021-08-05 18:00 UTC, shyim commented on changelog/_unreleased/2021-08-05-wrong-birthday-selected-if-empty.md
> +author_email: stephanłvierpunkt.de
email looks wrong

2021-08-05 18:00 UTC, shyim commented on changelog/_unreleased/2021-08-05-wrong-birthday-selected-if-empty.md
> +author: Stephan
should be the full name

2021-08-05 18:00 UTC, shyim commented on changelog/_unreleased/2021-08-05-wrong-birthday-selected-if-empty.md
> +* Query whether birthday is filled. Only then the variables for the select are generated.
```suggestion
* Changed twig template `src/Storefront/Resources/views/storefront/page/account/profile/personal.html.twig` to not preselect current day when no birthdate is provided
```

2021-08-05 19:01 UTC, shyim approved these changes

2021-08-11 14:21 UTC, Dominik28111 commented
Thanks for your contribution. Your PR will be merged as soon as our internal pipeline is green.

2021-08-11 15:33 UTC, closed without merging