Add EntityIndexingMessage::addSkip to add skipped contents more easily
shopware/platform pull request #2081
Opened 2021-09-22 18:34 UTC by JoshuaBehrens

### 1. Why is this change necessary?

Because of https://github.com/shopware/platform/pull/2082

### 2. What does this change do, exactly?

It adds addSkip to allow easier changing changing without having to call setSkip/getSkip/array_merge yourself.

### 3. Describe each step to reproduce the issue or behaviour.

To do https://github.com/shopware/platform/pull/2082

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-10-01 16:10 UTC, JoshuaBehrens commented
Rebased and changelogged

2021-10-04 12:45 UTC, mitelg commented
@JoshuaBehrens @NiklasLimberg 
shouldn't this be changed first in this PR? https://github.com/shopware/platform/blob/trunk/src/Core/Content/Product/DataAbstractionLayer/ProductIndexer.php#L133

2021-10-04 14:01 UTC, JoshuaBehrens commented
@mitelg I don't care the order. I can refactor the other PR later on. I don't care which one I edit but eventually I wasn't sure whether both changes are cool so I decided to separate them

2021-10-04 18:38 UTC, mitelg commented
I just wanted to give the hint 😉

2021-10-05 00:58 UTC, JoshuaBehrens commented
Aaah I see. The other is merged, the let me update my code here

2021-10-05 05:40 UTC, mitelg commented
that's what I wanted to say 😅👍
sorry 😇

2021-10-05 09:00 UTC, JoshuaBehrens commented
@mitelg there we go

2021-10-08 09:19 UTC, NiklasLimberg requested changes

2021-10-08 09:19 UTC, NiklasLimberg commented on src/Core/Framework/DataAbstractionLayer/Indexing/EntityIndexingMessage.php
> +    public function addSkip(string ...$skip): void
Hi @JoshuaBehrens,
please fix this ci issue:
Parameter #1 ...$skip of method Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexingMessage::addSkip() expects string, array<int, string> given.

2021-10-08 09:19 UTC, NiklasLimberg commented on src/Core/Framework/DataAbstractionLayer/Indexing/EntityIndexingMessage.php
> +        $this->skip = \array_merge($this->skip, \array_values($skip));
And maybe add an array_unique around it to ensure there are no duplicate values?

2021-10-29 19:48 UTC, JoshuaBehrens commented
I rebased and amend code to the feedback

2021-11-09 12:16 UTC, NiklasLimberg commented
Hi @JoshuaBehrens,
that was my first time using the new importer tool built by @shyim, didn't expect it to create a new ticket but whatever let's use the new ticket to make it easier for the new tool.

2021-11-09 12:22 UTC, JoshuaBehrens commented
I don't care the ticket code :) go for it anyway you like. Or shall I set the code in the changelog file?

2021-11-09 19:54 UTC, closed without merging

2021-11-12 11:14 UTC, keulinho commented
Hey @JoshuaBehrens, your changes are merged, thank you for your contribution. :blue_heart: :tada:

2021-11-12 11:29 UTC, JoshuaBehrens commented
You're welcome :) thank you for the merge