Add check/throw new error before deleting active addresses via sore-api
shopware/platform pull request #2133
Opened 2021-10-16 05:16 UTC by drjamesj

### 1. Why is this change necessary?
This PR addresses issue #2117 which identifies unexpected behaviour when deleting an active address via the store-api.

### 2. What does this change do, exactly?
Before deleting an address, in addition to checking if it is the default billing or shipping address (existing check), a further check is made to determine if it's the current active billing or shipping address based on the customer context. If so, it will throw an error.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create a new billing or shipping address for a logged in custom via store-api
2. Set the address as the active address by calling `PATCH /context`
3. Next delete the address by calling `DELETE /store-api/account/address/${addressId}`
4. Log out of the user
5. Log back into the user to be greeted with below error

```
Argument 1 passed to Shopware\Core\Checkout\Customer\CustomerEntity::setActiveBillingAddress() must be an instance of Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity, null given, called in /app/platform/src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php on line 478
```

### 4. Please link to the relevant issues (if any).
#2117 

### 5. Checklist
I am a first time contributor here, please let me know which (if any) of the following are required.

- [ ] I have written tests and verified that they fail without my change -- please let me know if this is required for this PR, and if so any instructions on how to do so would be appreciated
- [X] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes -- let me know if this is necessary
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2021-10-16 05:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/shopware/platform?pullRequest=2133) <br/>All committers have signed the CLA.

2021-10-18 09:13 UTC, shyim requested changes

2021-10-18 09:13 UTC, shyim commented on src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php
> +        if($addressId === $context->getCustomer()->getActiveBillingAddress()->getId()
Can you add a test case for this case? Thanks :smile:

2021-10-18 09:13 UTC, shyim commented
And a changelog file? :smile:

2021-10-18 12:51 UTC, drjamesj commented
@shyim Test case and changelog added. Please let me know any feedback :)

2021-10-20 11:15 UTC, closed without merging

2021-10-20 11:16 UTC, shyim commented
Thanks for your Contribution! :blue_heart: