update bootstrap docs url from v4 to v5 in bootstrap.scss
shopware/platform pull request #2443
Opened 2022-04-25 22:51 UTC by sawden

### 1. Why is this change necessary?
The bootstrap documentation in bootstrap.scss links to version 4. With the update to version 5, the link is misleading.

### 2. What does this change do, exactly?
Update the link in the scss for developers.

### 3. Describe each step to reproduce the issue or behaviour.
x

### 4. Please link to the relevant issues (if any).
x

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-04-25 22:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=2443) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=2443) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=2443) it.</sub>

2022-04-26 06:24 UTC, keulinho requested changes
Hey @sawden, thanks for your contribution! :tada: :blue_heart: 

Please accept the [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=2443), otherwise we can't accept your PR.

Besides that i have one little suggestion.

2022-04-26 06:24 UTC, keulinho commented on src/Storefront/Resources/app/storefront/src/scss/abstract/variables/_bootstrap.scss
> +https://getbootstrap.com/docs/5.0/customize/sass/#variable-defaults
Currently the default bootstrap version is still v4, v5 will only be used if you activate the feature flag for the next major version. Bootstrap v5 will be the default starting with v6.5.0.0.
What do you think of adding both documentation links:

```suggestion
Bootstrap 4 Docs
https://getbootstrap.com/docs/4.3/getting-started/theming/#variable-defaults
Bootstrap 5 Docs
https://getbootstrap.com/docs/5.0/customize/sass/#variable-defaults
```

2022-06-15 08:11 UTC, shyim commented
I will close this pull request as it's inactive. Feel free to create a new one, if you have updated it.

2022-06-15 08:11 UTC, closed without merging