NEXT-21659: Allow updating custom and credit line items without ALLOW_PRODUCT_PRICE_OVERWRITES permission, when no prices are being updated
shopware/platform pull request #2490
Opened 2022-05-18 10:02 UTC by rickschippers

Fix for NEXT-21659: Allow updating custom and credit line items without ALLOW_PRODUCT_PRICE_OVERWRITES permission, when no prices are being updated.

The product line item type only checks for this permission when a price_definition is set in the date -> so only when an actual price change occurs. 

Modified both the custom and credit type line items with similar behaviour.

https://issues.shopware.com/issues/NEXT-21659

2022-05-18 10:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=2490) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=2490) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=2490) it.</sub>

2022-05-18 14:32 UTC, keulinho requested changes
@rickschippers thanks for your contribution! :tada: :blue_heart: 

In general your changes look reasonable, i've just one little remark.

And additionally can you provide some test cases for your changes to the `\Shopware\Core\Checkout\Test\Cart\LineItemFactoryRegistryTest`? 

Maybe you can work with a [dataprovider](https://phpunit.readthedocs.io/en/stable/writing-tests-for-phpunit.html#data-providers) here that will provide the lineItem type and the payload that should be created or updated through the factory.

2022-05-18 14:32 UTC, keulinho commented on src/Core/Checkout/Cart/LineItemFactoryHandler/CreditLineItemFactory.php
> +        if (isset($data['priceDefinition']) && !$context->hasPermission(ProductCartProcessor::ALLOW_PRODUCT_PRICE_OVERWRITES)) {
Currently the same check is also used in the `create` method in both factories, IMHO we should remove that check completely from the `create` as the create will call the `update` internally 

Then the code will also follow the structure of the ProductLineItemFactory, as there too there is no permission check in the `create` only in the update.

2022-06-15 08:16 UTC, shyim commented
Hey,

I will close this pull request as it's inactive for a while. Feel free to create a new one, if you have updated your code.
Anyway thanks!

2022-06-15 08:16 UTC, closed without merging