make the used HttpCache-class customizable (similar to Kernel-class)
shopware/platform pull request #2589
Opened 2022-07-05 15:19 UTC by SvenHerrmann

### 1. Why is this change necessary?
I'd like to exchange the used HttpCache-class.

### 2. What does this change do, exactly?
It introduces an new property to Core\HttpKernel which can be set similar to the already existing $kernelClass-property.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-07-05 16:02 UTC, shyim requested changes

2022-07-05 16:02 UTC, shyim commented on src/Core/HttpKernel.php
> +    protected static $httpCacheClass = HttpCache::class;
Typehint string

2022-07-06 06:36 UTC, SvenHerrmann commented on src/Core/HttpKernel.php
> +    protected static $httpCacheClass = HttpCache::class;
done

2022-07-29 14:34 UTC, closed without merging

2022-07-29 20:19 UTC, dneustadt commented
Thank you for your contribution 😄