[NEXT-22268] Fix comparision channel generation with huge amount of data
shopware/platform pull request #2600
Opened 2022-07-13 12:26 UTC by yourborjia

### 1. Why is this change necessary?
Because `product_export_generate_task` run interval is 60 seconds, there is a possibility for "race condition" in case of feed generation time is more than 60 seconds.

### 2. What does this change do, exactly?
This change fixes an issue with feed generation with huge amounts of data. Additionally is fixes memory-related issue during export caused be weird League FS API, which not allows to "append" data to file without existing content overriding  (without FS adapter constructor manipulations).

### 3. Describe each step to reproduce the issue or behaviour.
1. Generate ~50k products;
2. Setup Comparison Sales Channel with simple template with any fields;
3. Run scheduled task worker and message consumer

As result, after feed generation for 1 minute, not finally generated `<sw_root>/files/export/<file_name>.partial` file will be overriden by newly scheduled `product_export_generate_task` and vice-versa. As result we will have incorrect file with missing products.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-22268
https://issues.shopware.com/issues/NEXT-19540

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-07-13 12:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=2600) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=2600) before we can accept your contribution.<br/><hr/>**Vladislav Borisenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=2600) it.</sub>

2022-07-15 08:08 UTC, OliverSkroblin requested changes

2022-07-15 08:08 UTC, OliverSkroblin commented on src/Core/Content/ProductExport/Struct/Specification/JobStuckSpecification.php
> +        if (!$value instanceof ProductExportEntity) {
please add correct type hint

2022-07-15 08:08 UTC, OliverSkroblin commented on src/Core/Content/ProductExport/Struct/Specification/SpecificationInterface.php
> +    public function isSatisfiedBy($value): bool;
why an interface? do you see some business cases that third party developers want to change this?

2022-07-15 08:08 UTC, OliverSkroblin commented on src/Core/Framework/Adapter/Filesystem/Plugin/AppendWrite.php
> +class AppendWrite extends AbstractPlugin
please create a wrapper instead of a plugin. Plugins are no longer supported in Flysystem

2022-07-17 18:51 UTC, yourborjia commented
Hey @OliverSkroblin! Could you please re-check this PR?

2022-09-30 07:37 UTC, mstegmeyer commented
Hey @yourborjia , excuse me for the very long response time. Unfortunately, our own responsible team has been fixing this issue simultaneously and the communication regarding this has not been working 🙈 
Our team reworked the `ProductExportGenerateTaskHandler` but did not do the AppendFilesystem stuff. We would still love to merge this part. Could you maybe have a look again and rebase onto the current trunk branch?

2022-11-14 07:41 UTC, shyim commented
Hey,

I will close it as it's inactive. Feel free to create a new one

2022-11-14 07:41 UTC, closed without merging