Added extension api datasets
shopware/platform pull request #2636
Opened 2022-08-04 15:23 UTC by JSalphanauten

### 1. Why is this change necessary?
To make more datasets available to the admin extension sdk.

### 2. What does this change do, exactly?
Used the code snippet provided by shopware(product detail) as template to make datasets available for several detail pages.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-08-04 15:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=2636) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=2636) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=2636) it.</sub>

2022-08-05 08:14 UTC, seggewiss requested changes
Looking really good so far 👍

2022-08-05 08:14 UTC, seggewiss commented on src/Administration/Resources/app/administration/src/module/sw-cms/page/sw-cms-detail/index.js
> +                id: 'sw-cms-detail__cms',
```suggestion
                id: 'sw-cms-detail__page',
```

2022-09-01 09:55 UTC, nfech01 approved these changes
Page is the correct naming.

2022-09-13 07:00 UTC, jleifeld commented
Can you have a look at the Jest tests? There are some failing tests which need to be fixed before we can merge it

2022-09-13 12:36 UTC, JSalphanauten commented
> Can you have a look at the Jest tests? There are some failing tests which need to be fixed before we can merge it

@jleifeld which test exactly are you talking about?
I haven't noticed dependencies to any test.

2022-09-13 12:43 UTC, jleifeld commented
> > Can you have a look at the Jest tests? There are some failing tests which need to be fixed before we can merge it
> 
> @jleifeld which test exactly are you talking about? I haven't noticed dependencies to any test.

You can execute the admin jest tests by following composer command:
`composer run admin:unit` or (for the watcher) `composer run admin:unit:watch`

Then you see the failing tests which needs to be fixed or updated

2022-11-10 12:19 UTC, jleifeld commented
I updated the tests and merged it to the platform.

2022-11-10 12:19 UTC, closed without merging