add criteria RangeAggregation
shopware/platform pull request #2670
Opened 2022-09-02 20:42 UTC by iNem0o

### 1. Why is this change necessary?

Allow to aggregate data on predefined ranges values for more flexibility in the DAL.

Bound are computed in SQL as in the elasticsearch native range aggregation :
   -> "from" will be compared with greater than or equal
   -> "to" will be compared with lower than

 
### 2. What does this change do, exactly?
# Core
* Add `RangeAggregation` and `RangeResult` 
* Add range aggregation parsing and hydration in `EntityAggregator`
* Add unit test on the aggregation range using database

# Elasticsearch
* Add range aggregation parsing in `CriteriaParser`
* Add range aggregation hydration in `ElasticsearchEntityAggregatorHydrator`
* Add `ElasticsearchRangeAggregation` to manage the conversion of DAL aggregation to elasticsearch
* Add unit test on the aggregation range using elasticsearch

### 3. Describe each step to reproduce the issue or behaviour.
```
$criteria = new Criteria();
$criteria->addAggregation(
    new RangeAggregation(
        'test-range-aggregation', 'price.gross',
        [
            ['from' => 5, 'to' => 10],
            ['from' => 10, 'to' => 15],
            ['from' => 15, 'to' => 30]
        ]
    )
);
```

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-09-05 18:46 UTC, shyim requested changes
Hey,

It looks overall very good 💙 . I added some comments. Thanks!

2022-09-05 18:46 UTC, shyim commented on changelog/_unreleased/2022-09-02-add-range-aggregation.md
> +# Elasticsearch
We don't have an Elasticsearch section. Add them to normal Core

2022-09-05 18:46 UTC, shyim commented on phpstan-baseline.neon
> +			message: "#^Parameter \\#2 \\$field of class Shopware\\\\Core\\\\Framework\\\\DataAbstractionLayer\\\\Search\\\\Aggregation\\\\Metric\\\\RangeAggregation constructor expects string, string\\|null
Please don't add new errors. can you solve it?

2022-09-05 18:46 UTC, shyim commented on src/Core/Framework/DataAbstractionLayer/Dbal/EntityAggregator.php
> +    private function parseDateHistogramAggregation(
Could you revert the style changes? So it's easier to see your differences?

2022-09-05 18:46 UTC, shyim commented on src/Elasticsearch/Test/Product/ElasticsearchProductTest.php
> +        ];
That looks like an inlined data provider. Can you add an actual dataProvider like the method above

2022-09-05 18:46 UTC, shyim commented on tests/unit/php/Core/Framework/DataAbstractionLayer/Search/Aggregation/Bucket/RangeAggregationTest.php
> +    public function buildRangeKeyDataProvider(): \Generator
```suggestion
    public function buildRangeKeyDataProvider(): iterable
```

2022-09-05 18:46 UTC, shyim commented on tests/unit/php/Core/Framework/DataAbstractionLayer/Search/Aggregation/Bucket/RangeAggregationTest.php
> +    public function buildRangeKeyDataProvider(): \Generator
You need here a return type phpdoc for phpstan

2022-09-05 18:46 UTC, shyim commented on src/Core/Framework/DataAbstractionLayer/Search/Aggregation/Metric/RangeAggregation.php
> + * @final tag:v6.5.0
Please add directly `final` to new classes

2022-09-05 18:46 UTC, shyim commented on src/Core/Framework/DataAbstractionLayer/Search/Aggregation/Metric/RangeAggregation.php
> +     * @return $this
You can remove phpdoc which doesn't add more value than the actual method parameter types

2022-09-05 18:46 UTC, shyim commented on tests/unit/php/Core/Framework/DataAbstractionLayer/Search/Aggregation/Bucket/RangeAggregationTest.php
> +    use IntegrationTestBehaviour;
Please move all Tests which needs a service container / connection to the integration folder. Unit folder should work plain without any traits / db connections

2022-09-05 18:46 UTC, shyim commented on src/Elasticsearch/Framework/ElasticsearchRangeAggregation.php
> +class ElasticsearchRangeAggregation extends AbstractAggregation
Can you add a simple unit test to this that the aggregation is crafted correct?

2022-09-05 20:51 UTC, iNem0o commented
Hi @shyim 

i have changed the PR accordingly

2022-09-06 08:22 UTC, shyim commented
@iNem0o Did you tested this also with date fields? 🤔

2022-09-06 08:57 UTC, iNem0o commented
It will fail because i used float parameters in the `addRange()` method. 
In my opinion this feature need a dedicated workflow with a `DateRangeAggregation` to allow more flexibility using custom date format and Date Math expressions in the ranges definitions as in the Elasticsearch core.

I updated the DAL documentation to precise that the ranges expects numerics.

2022-09-08 08:16 UTC, shyim commented
Could you maybe throw an exception when the target field cannot be used for that aggregation?

2022-09-14 14:18 UTC, iNem0o commented
Hi @shyim i added the field type validation

2022-12-05 18:45 UTC, closed without merging

2022-12-06 06:58 UTC, keulinho commented
Thanks again for your contribution, your PR was merged! :tada: :blue_heart:

2022-12-06 07:33 UTC, iNem0o commented
Nice ! :rocket:

Le mar. 6 déc. 2022, 07:58, Jonas Elfering ***@***.***> a
écrit :

> Thanks again for your contribution, your PR was merged! 🎉 💙
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shopware/platform/pull/2670#issuecomment-1338874662>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIXPM7EJDDFWJ4B76XFC3LWL3P2JANCNFSM6AAAAAAQDSKZ5E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>