Add sales filter to product filtering
shopware/platform pull request #2828
Opened 2022-11-04 13:50 UTC by MelvinAchterhuis

### 1. Why is this change necessary?

Adds a new filter for merchants so they can easily filter their best selling products

### 2. What does this change do, exactly?

Adds a new filter to the product filtering

### 3. Describe each step to reproduce the issue or behaviour.

N/A

### 4. Please link to the relevant issues (if any).

N/A

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-11-04 14:04 UTC, tinect requested changes

2022-11-04 14:04 UTC, tinect commented on src/Administration/Resources/app/administration/src/module/sw-product/snippet/de-DE.json
> +        "label": "Verkauf"
```suggestion
        "label": "Verkäufe"
```

2022-11-10 14:45 UTC, J-Rahe commented
Hey @MelvinAchterhuis,
your PR looks good so far, but could you add the option to also display the sales in the listing (same as with currencies)?

2022-11-10 19:24 UTC, MelvinAchterhuis commented
> Hey @MelvinAchterhuis, your PR looks good so far, but could you add the option to also display the sales in the listing (same as with currencies)?

@J-Rahe , how would you see this working with parent products that has no sales? A sum of al variant sales? (seems like me this could have an impact on the performance when the parent has a lot of variants)

2022-11-16 13:43 UTC, J-Rahe commented
Hey @MelvinAchterhuis, sorry that it took so long. I have now confirmed with the PO that:
1. The main listing should have the option to show the sales and just show an placeholder(e.g. "-") for variant products.
2. The variant listing (from the main listing and in the product tab) should have the same option to enable sales being shown, and will then show the sales for each variant.

2022-11-24 18:49 UTC, MelvinAchterhuis commented
@J-Rahe ,
I've updated the PR

2023-03-10 07:19 UTC, closed without merging

2023-03-10 07:55 UTC, keulinho commented
Thanks again for your contribution, your PR got finally merged! :tada: :blue_heart: