Add a hint on newsletter registration message, that the user might already be registered
shopware/platform pull request #2972
Opened 2023-02-10 12:49 UTC by amenk

### 1. Why is this change necessary?

During newsletter registration, no email is sent if the user trying to register is already registered. The current message does not reveal that and might lead to confusions.

### 2. What does this change do, exactly?

Make possible reasons for not receiving the email clearer in the message.

### 3. Describe each step to reproduce the issue or behaviour.

1. Register for the newsletter, confirm the registration
2. Try to register again

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [x] I have read the contribution requirements and fulfil them.

2023-06-07 15:41 UTC, amenk commented
What do you think?

2023-06-12 13:42 UTC, keulinho commented
@GitEvil as it is a snippet change, can you take a look here?

2023-06-19 15:04 UTC, GitEvil requested changes
Hi Alexander, wenn wir hier den User etwas mehr an die Hand nehmen wollen, dann auch richtig. Meine nächste Frage wäre jetzt nämlich, wie ich denn rausfinden kann, ob ich bereits registriert bin. ;) Ist dann natürlich lang, aber irgendeinen Tod muss man ja sterben, denk ich.

2023-06-19 15:04 UTC, GitEvil commented on src/Storefront/Resources/snippet/de_DE/storefront.de-DE.json
> +    "subscriptionPersistedInfo": "Sollten Sie keine Mail erhalten haben, sind Sie eventuell bereits für den Newsletter registriert. Falls nicht, wiederholen Sie den Vorgang oder wenden Sie sich an de
```suggestion
    "subscriptionPersistedInfo": "Sollten Sie keine E-Mail erhalten, sind Sie eventuell bereits für den Newsletter angemeldet. Durchsuchen Sie Ihren Posteingang und Spamordner und wiederholen Sie gegebenenfalls die Anmeldung. Falls auch das nicht funktioniert, wenden Sie sich bitte an unseren Support.",
```

2023-06-19 15:04 UTC, GitEvil commented on src/Storefront/Resources/snippet/en_GB/storefront.en-GB.json
> +    "subscriptionPersistedInfo": "If you did not receive any email, you might already be registered for our newsletter. If not, please repeat the process or contact our support team.",
```suggestion
    "subscriptionPersistedInfo": "If you do not receive an email, you may already be subscribed to the newsletter. Check your inbox and spam folder and repeat the registration if necessary. If this does not work either, please contact our support.",
```

2023-06-19 15:51 UTC, amenk commented
@GitEvil sure, thanks :-) / Klar gerne :-)

2023-06-30 10:59 UTC, shyim commented on src/Storefront/Resources/snippet/de_DE/storefront.de-DE.json
> +    "subscriptionPersistedInfo": "Sollten Sie keine Mail erhalten haben, sind Sie eventuell bereits für den Newsletter registriert. Falls nicht, wiederholen Sie den Vorgang oder wenden Sie sich an de
@amenk can you apply this too?

2023-06-30 12:46 UTC, amenk commented
@shyim second commit applied, thanks for pointing out ... can you squash this on merge?

2023-06-30 12:50 UTC, shyim commented
Sure. we will take over :)

2023-06-30 16:22 UTC, silverDuy commented on changelog/_unreleased/2023-02-10-improve-newsletter-registration-text.md
> +* Add a hint on newsletter registration message, that the user might already be registered
```suggestion
* Changed `src/Storefront/Resources/snippet/en_GB/storefront.en-GB.json` by changing the content of the translation key `newsletter.subscriptionPersistedInfo` to add a hint on the newsletter registration message that the user might already be registered.
* Changed `src/Storefront/Resources/snippet/de_DE/storefront.de-DE.json` by changing the content of the translation key `newsletter.subscriptionPersistedInfo` to add a hint on the newsletter registration message that the user might already be registered.
```

2023-11-27 10:36 UTC, closed without merging

2023-11-27 10:48 UTC, bschulzebaek commented
Hey @amenk, we've just merged the change. Thanks again for your contribution 🙂