Add `contentPadding` prop for `sw-card` component
shopware/platform pull request #3021
Opened 2023-03-21 08:48 UTC by crisalder2806

### 1. Why is this change necessary?
This change adds the ability to add/remove padding of the `sw-card` component content which sometimes is not necessary/needed on the UI.

### 2. What does this change do, exactly?
Add `contentPadding` property to `sw-card` component to add/remove card content padding.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2023-03-21 15:15 UTC, keulinho commented
@shopware/ct-admin can you take a look here?

2023-03-21 15:18 UTC, jleifeld requested changes

2023-03-21 15:18 UTC, jleifeld commented on src/Administration/Resources/app/administration/src/app/component/base/sw-card/index.js
> +            default: false,
Default value should be `true`. Every card should have content padding by default.

2023-03-21 15:18 UTC, jleifeld commented on src/Administration/Resources/app/administration/src/app/component/base/sw-card/sw-card.spec.js
> +    it('should not have content padding', async () => {
Add also a test where the card should have content padding

2023-03-22 06:42 UTC, crisalder2806 commented on src/Administration/Resources/app/administration/src/app/component/base/sw-card/index.js
> +            default: false,
@jleifeld All comments are resolved. Please help me to check again. Thank you.

2023-11-21 10:09 UTC, jleifeld approved these changes

2023-11-24 14:55 UTC, closed without merging

2024-01-03 09:37 UTC, mitelg commented
thanks for your contribution @crisalder2806 👍🎉💙