WIP  Allow admin customer login
shopware/platform pull request #3278
Opened 2023-08-21 21:44 UTC by ugurkankya

### 1. Why is this change necessary?
Currently it is not possible to login as customer from administration

### 2. What does this change do, exactly?
Adds a new button "Login as customer" next to "Edit" after clicking the button a modal with sales channels list will be shown.
Token will be generated to ensure not everyone can guess the token, the token will be validated on the storefront & store api side as well.

![Bildschirmfoto 2022-09-24 um 00 27 24](https://user-images.githubusercontent.com/27974830/192064928-961dc566-b0ae-43a9-8480-98d80e32b037.png)

![Bildschirmfoto 2022-09-28 um 00 03 02](https://user-images.githubusercontent.com/27974830/192645712-bf4d9f69-532c-43bb-961b-8a2974bed195.png)

### 3. Describe each step to reproduce the issue or behaviour.
Administration -> Customers -> Overview select a customer after clicking on "Login as customer" you should see a modal "Select the sales channel below you wish to perform the login". 
Click on the sales channel you like and you should be redirected to the storefront like you would normal login.
Cart and Context should be restored.

### 4. Please link to the relevant issues (if any).
[https://github.com/shopware/platform/pull/1572](https://github.com/shopware/platform/pull/1572)
[https://github.com/shopware/platform/issues/878](https://github.com/shopware/platform/issues/878)

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2023-08-21 21:48 UTC, ugurkankya commented
I have opened a new pull request, since i have accidentally destroyed my changes so github was not showing changed files.

Old PR: [https://github.com/shopware/platform/pull/2701](https://github.com/shopware/platform/pull/2701)

2023-08-22 11:23 UTC, PheysX commented
Push fast 😆

2023-08-25 10:43 UTC, shyim commented on src/Core/Checkout/Customer/LoginAsCustomerTokenGenerator.php
> +        return hash_hmac('sha1', json_encode($tokenData), $this->appSecret);
can we use atleast `sha256`, sha1 is insecure and should not be used I guess

2023-08-25 11:33 UTC, shyim requested changes

2023-08-25 11:33 UTC, shyim commented on src/Core/Checkout/Customer/SalesChannel/LoginAsCustomerRoute.php
> +            $data->set(self::SALES_CHANNEL_ID, $salesChannelIdFromContext);
this should always be true

2023-08-25 11:33 UTC, shyim commented on src/Core/Checkout/Customer/SalesChannel/LoginAsCustomerRoute.php
> +        }
seems duplicate

2023-08-25 11:33 UTC, shyim commented on src/Core/Checkout/Customer/SalesChannel/LoginAsCustomerRoute.php
> +class LoginAsCustomerRoute extends AbstractLoginAsCustomerRoute
`LoginCustomerWithTokenRoute` maybe?

2023-08-25 11:33 UTC, shyim commented on src/Core/Framework/Api/Controller/SalesChannelProxyController.php
> +        $salesChannelId = (string) $request->request->get('salesChannelId');
you can use your constant here again

2023-08-25 11:33 UTC, shyim commented on src/Core/Framework/Api/Controller/SalesChannelProxyController.php
> +        }
Maybe move higher so you don't have to fetch the sales channel

2023-08-25 11:33 UTC, shyim commented on src/Core/Framework/Api/Controller/SalesChannelProxyController.php
> +        $response->setContent($content ?: null);
return new JsonResponse with that as array

2023-08-25 11:33 UTC, shyim commented on src/Core/Framework/Api/Controller/SalesChannelProxyController.php
> +        /** @var CustomerEntity|null $customer */
When you add type the `customerRepository` property itself `EntityRepository<CustomerCollection>` you can remove this line.

2023-08-25 11:33 UTC, shyim commented on src/Core/Framework/Api/Controller/SalesChannelProxyController.php
> +            throw new InvalidSalesChannelIdException($customerId);
this exception looks wrong, you check for customer and throw a sales channel exception.

2023-08-25 11:33 UTC, shyim commented on src/Core/Framework/Api/Exception/InvalidCustomerIdException.php
> +class InvalidCustomerIdException extends ShopwareHttpException
Can you add this to CustomerException? and is this maybe just customerNotFound instead of invalid?

2023-08-25 11:33 UTC, shyim commented on src/Storefront/Controller/AuthController.php
> +        }
I guess you need to add proper errors to `addFlash` to give the user feedback.

2023-08-25 17:43 UTC, ugurkankya commented
@keulinho 

I do not see any security issue since i am validating the token in the storefront, so just guessing the customerId would not be enough. 

If we move the logic to the admin-api how we can login the customer? I can not access the session from storefront in the admin api, even so it would still i think a bad practise.

@shyim What do you think about that situation?

2023-08-25 20:24 UTC, ugurkankya commented
I think i found the solution about admin auth in storefront by using `_routeScope => 'api' `it seems working :)

2024-05-13 14:59 UTC, sobyte commented
Any news on this? :)

2024-05-14 10:38 UTC, sobyte commented
@ugurkankya I hope that you don't mind that I've continued your work and opened #3713

2024-05-14 19:18 UTC, ugurkankya commented
> @ugurkankya I hope that you don't mind that I've continued your work and opened #3713

Thank you for your help i really appreciate it

2024-05-15 05:05 UTC, mitelg commented
I will close this then in favour of the new PR

2024-05-15 05:05 UTC, closed without merging