Fix thumbnail generation for command line
shopware/platform pull request #3748
Opened 2024-06-05 14:37 UTC by mschop

When thumbnails are generated with -s flag, the thumbnail files are generated and directly removed, because the MediaDeletionSubscriber does delete the thumbnail files asynchronous via queue.

By setting the flag in the context, we can prevent that the deletion is done asynchronously.

### 1. Why is this change necessary?
It fixes the bug, that thumbnails are directly deleted after generation if invoked via command line `bin/console media:generate-thumbnails -s`.

### 2. What does this change do, exactly?
See above.

### 3. Describe each step to reproduce the issue or behaviour.

1. Delete all thumbnails.
2. Run `bin/console media:generate-thumbnails -s`

### 4. Please link to the relevant issues (if any).
None. I didn't create one yet.

### 5. Checklist

- [ x ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes -> none required / bugfix
- [ x ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2024-06-05 14:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=3748) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=3748) before we can accept your contribution.<br/><hr/>**Martin Schophaus** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=3748) it.</sub>

2024-06-07 10:04 UTC, marcelbrode requested changes
Beside those minor issues, this looks fine to me, I'll ask a more backend focus colleague to have a look at it as well.

In any case, please add some tests for your change :)

2024-06-07 10:04 UTC, marcelbrode commented on src/Core/Content/Media/Commands/GenerateThumbnailsCommand.php
> +	$context->addState(MediaDeletionSubscriber::SYNCHRONE_FILE_DELETE);
Please indent

2024-06-07 10:04 UTC, marcelbrode commented on src/Core/Content/Media/Message/GenerateThumbnailsHandler.php
> +	    $criteria->addFilter(new EqualsAnyFilter('media.id', $msg->getMediaIds()));
Please keep empty spaces instead of tabs

2024-06-07 10:04 UTC, marcelbrode commented on changelog/_unreleased/2024-06-05-fix-thumbnail-generation-via-command-line.md
> +* Fix thumbnail generation via command line for -s flag
```suggestion
* Fix thumbnail generation via command line for -s flag
```
Please always start your changelog with "Added", "Remove", "Changed" or "Deprecated"

2024-06-18 09:38 UTC, marcelbrode commented
Hi there! Any updates on this ticket?

2024-07-02 07:47 UTC, marcelbrode commented
Since we noticed no changes in the last 4 weeks, I'll close this ticket. Feel free to ping me, if you've rebased your branch and provided the changes asked and I will gladly reopen this ticket. Thank you :smile:

2024-07-02 07:47 UTC, closed without merging

2024-07-02 10:53 UTC, mschop commented on src/Core/Content/Media/Commands/GenerateThumbnailsCommand.php
> +	$context->addState(MediaDeletionSubscriber::SYNCHRONE_FILE_DELETE);
Done

2024-07-02 10:53 UTC, mschop commented on src/Core/Content/Media/Message/GenerateThumbnailsHandler.php
> +	    $criteria->addFilter(new EqualsAnyFilter('media.id', $msg->getMediaIds()));
Done

2024-07-02 10:53 UTC, mschop commented on changelog/_unreleased/2024-06-05-fix-thumbnail-generation-via-command-line.md
> +* Fix thumbnail generation via command line for -s flag
Done

2024-07-02 11:33 UTC, mschop commented
@marcelbrode

Sorry, that it took so long. I am running very low on time.

I changed the things you mentioned and rebased the branch.

I currently don't have the time yet to add proper automated tests for this functionality. Could some developer on your side add that?

2024-07-03 10:54 UTC, mitelg commented
would you mind recreating the PR? I could not reopen it here :thinking:

2024-07-03 11:01 UTC, mschop commented
@mitelg Done: https://github.com/shopware/shopware/pull/3792