Dynamic properties
shopware/platform pull request #3840
Opened 2024-08-09 07:52 UTC by raphael-homann

### 1. Why is this change necessary?
Many deprecated are present in my php log.
For example : Deprecated: Creation of dynamic property Shopware\Core\Content\Category\CategoryEntity::$parentVersionId is deprecated

### 2. What does this change do, exactly?
It allows to set fields that are not declared

### 3. Describe each step to reproduce the issue or behaviour.
open the deprecation log, and navigate on the storefront

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2024-08-09 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=3840) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=3840) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=3840) it.</sub>

2024-08-09 08:05 UTC, mitelg requested changes

2024-08-09 08:05 UTC, mitelg commented on src/Core/Framework/DataAbstractionLayer/Entity.php
> +#[AllowDynamicProperties]
we should not allow dynamic properties. instead the missing ones should be added

2024-08-09 08:05 UTC, mitelg commented on src/Core/Framework/Struct/Struct.php
> +#[AllowDynamicProperties]
same for this

2024-08-09 08:16 UTC, raphael-homann reviewed
Hello, 
Thanks for your answer. 

So, what abour "parentVersionId" in CategoryEntity ?
I have  many "versionId" missing, in my own entities, but also in the core.

Should we add all missing fields ?

2024-08-09 09:02 UTC, mitelg commented
yes, that would be indeed the correct fix. the attribute should imo only be used where actual dynamic properties are used. in our case the properties are representing database columns defined in the entity definition. so they need to be present. see https://github.com/shopware/shopware/blob/trunk/src/Core/Content/Category/CategoryDefinition.php#L115

which are the ones, that are also missing?

2024-08-26 07:32 UTC, keulinho commented
Hey @raphael-homann, thanks for your contribution, but as @mitelg said instead the missing fields should be added to the entities. There was a reason why this behaviour was deprecated in PHP itself, as it makes the code way harder to understand and super easy to introduce bugs, when you rely in dynamic properties. Therefore we discourage the use of the `AllowDynamicProperties` Attribute, but instead we should add all the fields to get type safety etc.

If there are cases where props are missing in core entities, feel free to add a new PR adding those, but i will close this PR right now as we don't want to go in that direction.

For context please refer to the RFC on PHP itself: https://wiki.php.net/rfc/deprecate_dynamic_properties

2024-08-26 07:32 UTC, closed without merging