Make Sales Channel Entrypoints configurable
shopware/platform pull request #4959
Opened 2024-10-04 12:53 UTC by runelaenen

### 1. Why is this change necessary?
Currently there are 3 usable entrypoints (main navigation, service navigation and footer navigation). If it is necessary to add an additional entrypoint there are lots of hoops to jump through to make this possible.

### 2. What does this change do, exactly?
To make this easier this change introduces a new Event that gathers custom entrypoints.
The current 'core' entrypoints are unchanged, so the additions in this PR are entirely backwards compatible.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2024-10-16 07:12 UTC, marcelbrode commented on src/Core/Content/Category/SalesChannel/SalesChannelEntrypointCollection.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-16 07:13 UTC, marcelbrode commented on src/Core/Content/Category/Event/SalesChannelEntrypointEvent.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-16 07:17 UTC, marcelbrode requested changes
A small one, but please adjust the area 🙂

2024-10-16 07:17 UTC, marcelbrode commented on src/Core/Content/Category/SalesChannel/SalesChannelEntrypointCollection.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-16 07:17 UTC, marcelbrode commented on src/Core/Content/Category/Event/SalesChannelEntrypointEvent.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-16 07:17 UTC, marcelbrode commented on src/Core/Content/Category/SalesChannel/SalesChannelEntrypointController.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-16 07:17 UTC, marcelbrode commented on src/Core/Content/Category/SalesChannel/SalesChannelEntrypointRoute.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-16 07:17 UTC, marcelbrode commented on src/Core/Content/Category/SalesChannel/SalesChannelEntrypointRouteResponse.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-16 07:17 UTC, marcelbrode commented on src/Core/Content/Category/SalesChannel/SalesChannelEntrypointService.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-16 07:17 UTC, marcelbrode commented on src/Core/Content/Category/SalesChannel/SalesChannelEntrypointStruct.php
> +#[Package('inventory')]
```suggestion
#[Package('buyers-experience')]
```

2024-10-17 08:50 UTC, MartinKrzykawski commented
Hello @runelaenen,

thank you very much for your contribution!

Since this is a significant change, it would be helpful if you could provide more details about it:

	1.	More context: What is the current state, and where do you see the issue?
	2.	What approach did you take to solve the issue?
	3.	How can I test it? This would help us better understand the changes and see the affected areas.

Thanks in advance!

2024-11-08 08:54 UTC, marcelbrode commented
Hi there! Any updates on this ticket?

2024-11-18 08:44 UTC, marcelbrode commented
Since we noticed no changes in the last 4 weeks, I'll close this ticket. Feel free to ping us, if you've rebased your branch and provided the changes asked and I will gladly reopen this ticket. Thank you :smile:

2024-11-20 13:02 UTC, tomm1996 commented
@runelaenen @marcelbrode I would be down to pick this issue up if you don't have time for it. Being able to define custom navigations is a pretty essential feature imo

2024-11-21 08:05 UTC, marcelbrode commented
> @runelaenen @marcelbrode I would be down to pick this issue up if you don't have time for it. Being able to define custom navigations is a pretty essential feature imo

I personally do not have a problem with that. Dunno about @runelaenen, thou.

2024-11-21 08:20 UTC, runelaenen commented
Hi @tomm1996 Go for it! My schedule unfortunately will not allow me to work on this a lot in the coming weeks. If you have any questions or if you want to ping-pong about something, hit me up on slack! :)

2024-11-25 09:28 UTC, marcelbrode commented
@tomm1996 Reopend it for you

2024-12-03 09:18 UTC, marcelbrode commented
@tomm1996
Hi there! Any updates on this ticket?

2024-12-05 15:09 UTC, tomm1996 commented
Hi @marcelbrode unfortunately I haven't gotten around to it yet, I will try to this weekend

2024-12-06 08:53 UTC, marcelbrode commented
> Hi @marcelbrode unfortunately I haven't gotten around to it yet, I will try to this weekend

Okay :) You can - of course - take your time, but I suggest to create a draft, since we're closing tickets after some weeks of inactivity, if it's not a draft.

Thanks again!

2024-12-06 09:20 UTC, mitelg commented
@marcelbrode then he would need to create a new PR :slightly_smiling_face: I don't know if we should do it anyway :thinking:

2024-12-10 10:25 UTC, tomm1996 commented
@marcelbrode @mitelg in that case feel free to close and @ me here if the feature is still desired. I will then create a new PR with the necessary adjustments

2024-12-10 10:39 UTC, closed without merging

2024-12-10 10:39 UTC, mitelg commented
I closed this PR of the original creator @runelaenen 

@marcelbrode please decided if you still want that, so that @tomm1996 can make the necessary steps :blush:

2024-12-11 09:03 UTC, MartinKrzykawski commented
Hey,

we discussed this topic internally and are unsure if we want to proceed with this change. Can you provide real-life scenarios where it would make sense to replace the entryPointIds using an event-based approach? These IDs always refer to the footer, service, and navigation category IDs, which are tied to the sales channel. To us, this seems more like a matter of proper configuration rather than something that requires extensibility.

Looking forward to your thoughts!

2024-12-11 10:15 UTC, runelaenen commented
Hi @MartinKrzykawski  We have multiple projects where more navigation entrypoints are necesary than the provided three. 

For example
- main menu
- secondary main menu
- service menu
- footer menu