Add Twig functions and tokens with inheritance alternatives
shopware/platform pull request #4980
Opened 2024-10-05 07:54 UTC by JoshuaBehrens

### 1. Why is this change necessary?

There are plugins out there, that make use of the Twig function `block` to include another's template block. This is nice to reuse code but does not check the inheritance and therefore fails to include other changes. The plugin author will be requested to use this code afterwards.

### 2. What does this change do, exactly?

I copied/reused functions or token parsers from Twig and made sure, they are checking the inheritance so you use all Twig ways to build your templates with all benefits of the plugin system.

### 3. Describe each step to reproduce the issue or behaviour.

* Add `sw_block` function as alternative to `block` but with inheritance
* Add `sw_source` function as alternative to `source` but with inheritance
* Add `sw_include` function as alternative to `sw_include` token
* Add `sw_use` token as alternative to `use` but with inheritance
* Add `sw_from` token as alternative to `from` but with inheritance
* Add `sw_import` token as alternative to `import` but with inheritance
* Add `sw_embed` token as alternative to `embed` but with inheritance
* Use `sw_block` in templates, which results in same cache but as a better example

### 4. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes ( https://github.com/shopware/docs/issues/1500 )
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

2024-10-09 06:45 UTC, BrocksiNet commented
Hi, @JoshuaBehrens :wave: First of all, great PR, and thx for that contribution!

Currently, the Storefront Team is aiming for less inheritance or, in other words, well-defined places for inheritance because the community also complained about too many breaks in the storefront area. This is also why we have the discussion about the [Storefront Future](https://github.com/shopware/shopware/discussions/4856).

So, from an extension point of view, this change makes a lot of sense. I am just wondering about the maintenance and if this will complicate things. And what should I use when I, as an extension developer, want to create a block without any inheritance? We need to test this a lot, explain it in Docs, and make sure that more TWIG functions do not make the system slower.

We will come back to you. Will take some time. Anyway, good work. :muscle:

2024-10-09 11:55 UTC, JoshuaBehrens commented
@BrocksiNet thank you for the feedback.

At first: the reason why I made this was an update in a plugin from a well-known plugin manufacturer, that referenced an OG Shopware file using the Twig block function. So some people are not aware, that not everything is inheritance aware. I shared my playground from the hacktoberfest event https://gist.github.com/JoshuaBehrens/f528e643adcd8c3b0a306b3bb7a44088 to verify things work.

I noticed the discussion and I feel like sw_embed would fit right in there. So I do not see it contrary to it but rather supporting that point.

I added some tests so I hope there are maybe just some other code path tests missing, that you can add.

I added some docs with reference to the Symfony docs. So I do not think we are missing any documentation. With the point some parts of your public communication claim: when you know Symfony, you have a headstart in working with Shopware. But when Twig is only covered partially it is rather a hassle than helpful. So I think this is a missing step we had to take.

2024-11-29 13:04 UTC, BrocksiNet commented
@JoshuaBehrens, I have prepared everything and have some internal approvals.

We want to merge this with 6.7 because we can't foresee what will change for a shop due to these new inheritances. 

Is that okay with you? Or do you not see any problems or breaks that could occur?

2024-11-29 14:42 UTC, JoshuaBehrens commented
@BrocksiNet I intended my work to behave without breaking changes I see your concerns though. If we can have a separate feature flag, I am fine with that :) because I need it :D 

And please make sure my name is on the commit. sounds weird but in the recent past some cherry-picks or however you (as a company) take the commits over were just with the person on your side and one feels to be less part of the project especially with big changes like this :/

2024-12-17 08:52 UTC, BrocksiNet commented
Added the [new PR](https://github.com/shopware/shopware/pull/5869) with all the changes needed. Currently as Draft.

2025-01-16 23:15 UTC, JoshuaBehrens commented
@BrocksiNet I already checked "Allow edits and access to secrets by maintainers" how shall we proceed? I offer to rebase :) anything else?

2025-02-03 09:43 UTC, mitelg commented on src/Core/Framework/Adapter/Twig/Extension/NodeExtension.php
> +     * @deprecated tag:v6.7.0  - replace TemplateFinder with TemplateFinderInterface
```suggestion
     * @deprecated tag:v6.8.0  - replace TemplateFinder with TemplateFinderInterface
```

it is too late for 6.7 :grin:

2025-02-03 10:08 UTC, BrocksiNet commented on src/Core/Framework/Adapter/Twig/Extension/NodeExtension.php
> +     * @deprecated tag:v6.7.0  - replace TemplateFinder with TemplateFinderInterface
Oh no :scream: Not a big problem I guess ... this can wait

2025-02-03 10:49 UTC, BrocksiNet commented
In my opinion, this is okay now. 

@JoshuaBehrens, could you test again because of the twig update to see if everything works as expected?

I do not trust the `codecov` number, to be honest ... -15.18% sounds like a lot ... any suggestions? :face_with_diagonal_mouth:

2025-02-03 13:03 UTC, keulinho commented on src/Core/Framework/Adapter/Twig/TokenParser/EmbedTokenParser.php
> +final class EmbedTokenParser extends \Twig\TokenParser\IncludeTokenParser
Should we mark all of those classes as internal? Just to be free in the future to react to changes, this should be the case for everything in adapter/twig

2025-02-04 07:21 UTC, BrocksiNet commented on src/Core/Framework/Adapter/Twig/TokenParser/EmbedTokenParser.php
> +final class EmbedTokenParser extends \Twig\TokenParser\IncludeTokenParser
Done :white_check_mark:

2025-02-09 17:19 UTC, JoshuaBehrens commented
@BrocksiNet I rebased and sqashed some commits/parts of commits to cleanup the history a bit. After re-reviewing my own code, I saw, that the EmbedTokenParser depends on an internal class from Twig. I changed it by copying over that specific piece of code.

There are some issues around bc-checks, but they were introduced by you adding internal. Is this something irrelevant as we are only having major changes on trunk?

You already updated the code to match new twig code. We have tests. We have a(n improved 💙) changelog. Anything that is missing out?

2025-02-10 09:08 UTC, mitelg requested changes

2025-02-10 09:08 UTC, mitelg commented on .bc-exclude.php
> +        // Class is marked as @internal (can be removed after merge to 6.7)
do we still need that? bc checker is currently disabled. if we want to deprecate something, this needs to be done for 6.8

2025-02-10 09:08 UTC, mitelg commented on changelog/_unreleased/2024-10-04-add-twig-functions-and-tokens-with-their-alternatives-with-inheritance.md
> +* Added Twig function `sw_block`, that must be used, when the template reference is used and inheritance is expected
do we want to deprecate the usage of the default Twig tokens and functions? :thinking: 

do we need to ensure, that only the new ones are used?

2025-02-10 09:08 UTC, mitelg commented on src/Core/Framework/Adapter/AdapterException.php
> +            self::INVALID_ARGUMENT,
if it is the `INVALID_ARGUMENT` code, you should use the already existing exception method. if not, define a new code

2025-02-10 09:08 UTC, mitelg commented on src/Core/Framework/Adapter/Twig/Extension/TwigFeaturesWithInheritanceExtension.php
> +class TwigFeaturesWithInheritanceExtension extends AbstractExtension
please mark all the new classes as internal

2025-02-10 10:30 UTC, BrocksiNet commented on src/Core/Framework/Adapter/Twig/Extension/TwigFeaturesWithInheritanceExtension.php
> +class TwigFeaturesWithInheritanceExtension extends AbstractExtension
![image](https://github.com/user-attachments/assets/16358721-f3d0-4a5b-b3ba-d6db1f6627e0)

Hmmm my local file looks different 🤔

2025-02-10 12:10 UTC, BrocksiNet commented on changelog/_unreleased/2024-10-04-add-twig-functions-and-tokens-with-their-alternatives-with-inheritance.md
> +* Added Twig function `sw_block`, that must be used, when the template reference is used and inheritance is expected
What would be the benefit of forcing this?

2025-02-10 12:14 UTC, keulinho commented on src/Core/Framework/Adapter/Twig/Extension/TwigFeaturesWithInheritanceExtension.php
> +class TwigFeaturesWithInheritanceExtension extends AbstractExtension
is internal now

2025-02-10 12:15 UTC, keulinho commented on src/Core/Framework/Adapter/Twig/TokenParser/MacroOverrideTokenParserMacro.php
> - * @internal
why do we remove the internal here?

2025-02-10 12:21 UTC, BrocksiNet commented on src/Core/Framework/Adapter/Twig/TokenParser/MacroOverrideTokenParserMacro.php
> - * @internal
I guess BC Checker was unhappy about that 🤔 But I can add and exclude it again.

2025-02-10 13:33 UTC, mitelg commented on changelog/_unreleased/2024-10-04-add-twig-functions-and-tokens-with-their-alternatives-with-inheritance.md
> +* Added Twig function `sw_block`, that must be used, when the template reference is used and inheritance is expected
proper inheritance in all places? :man_shrugging: I just wanted to know, if this is not necessary, we can leave it like this

2025-02-10 13:33 UTC, mitelg commented on src/Core/Framework/Adapter/Twig/TokenParser/MacroOverrideTokenParserMacro.php
> - * @internal
we should make sure, that every class in the twig adapter namespace is internal. in general all classes in the adapter namespace should be internal

2025-02-10 13:50 UTC, BrocksiNet commented on changelog/_unreleased/2024-10-04-add-twig-functions-and-tokens-with-their-alternatives-with-inheritance.md
> +* Added Twig function `sw_block`, that must be used, when the template reference is used and inheritance is expected
The main question is: Does the developer know that when he uses just `block` he only has a single inheritance? Maybe this is what he wants, and that would be okay with me. Or is he just using block because he copied that somewhere from Twig docs and does not know the difference between `sw_block` (multi inheritance)?

We need to explain the differences, but we should not favor one over the other. And, of course, we cannot prevent some from being used with the wrong intention due to a lack of knowledge.

2025-02-10 14:29 UTC, mitelg commented on changelog/_unreleased/2024-10-04-add-twig-functions-and-tokens-with-their-alternatives-with-inheritance.md
> +* Added Twig function `sw_block`, that must be used, when the template reference is used and inheritance is expected
sure :+1: I just thought it could be confusing, because sometimes you can and sometimes you have to use `sw_*` stuff :slightly_smiling_face: (e.g. sw_extends)

2025-02-10 14:30 UTC, mitelg approved these changes

2025-02-11 08:13 UTC, keulinho approved these changes

2025-02-11 19:01 UTC, merged

2025-02-12 08:06 UTC, mitelg commented
thanks for your contribution @JoshuaBehrens 👍🎉💙

2025-02-12 14:12 UTC, JoshuaBehrens commented
Thank you for working it out together :)

2025-04-09 04:57 UTC, nguyenquocdaile commented
Hi @JoshuaBehrens , For the changes you have suggested in the commercial plugin when replacing `block` to `sw_block`
```
{% block swag_advanced_search_suggest_result_link %}
					{{ block('layout_search_suggest_result_link', '@Storefront/storefront/layout/header/search-suggest.html.twig') }}
				{% endblock %}
```
to
```
{% block swag_advanced_search_suggest_result_link %}
					{{ sw_block('layout_search_suggest_result_link', '@Storefront/storefront/layout/header/search-suggest.html.twig') }}
				{% endblock %}
```
We found an issue with the rendering HTML element
![image](https://github.com/user-attachments/assets/17096395-cbed-4cd4-85aa-3af5906db27a)

So the solution here we will and a raw filter if we use sw_block
```
{% block swag_advanced_search_suggest_result_link %}
					{{ sw_block('layout_search_suggest_result_link', '@Storefront/storefront/layout/header/search-suggest.html.twig') |raw }}
				{% endblock %}
```

Just raise it here when someone has met the issue.
Thanks

2025-04-09 11:42 UTC, JoshuaBehrens commented
@nguyenquocdaile thank you for point out :)