NEXT-28685 - Move cheapestPrice to ProductDefinition
shopware/platform pull request #5174
Opened 2024-10-18 20:17 UTC by florianliebig

### 1. Why is this change necessary?

Dynamic product group with "Price" filter creates error when adding / searching the products in sales channel products.

### 2. What does this change do, exactly?

Move the `cheapestPrice` field from `SalesChannelProductDefinition` up to its parent `ProductDefinition`

### 3. Describe each step to reproduce the issue or behaviour.

Setup fresh shopware instance with dummy data

Create dynamic product group with these settings

![CleanShot 2024-10-18 at 22 14 57@2x](https://github.com/user-attachments/assets/ede785f5-b22c-40f2-95f1-983b9dbf4267)

Go to SalesChannel -> Products -> Add Products -> Product group selection -> search for created product group and select

Error `Field "cheapestPrice" in entity "product" was not found`

![CleanShot 2024-10-18 at 22 16 48@2x](https://github.com/user-attachments/assets/797caa49-6e83-4762-b74c-3c43d4776a67)

On ProductEntity

### 4. Please link to the relevant issues (if any).

https://github.com/shopware/shopware/issues/4889

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfill them.

2024-10-18 20:25 UTC, OliverSkroblin commented
The cheapest price was moved from the Product Definition to the Sales Channel Definition due to significant performance and memory consumption concerns.

2024-10-19 07:48 UTC, florianliebig commented
Good point @OliverSkroblin - was thinking the same, but struggling to find a way to query SalesChannelProducts. Will investigate on that and most likely open a new PR

2024-10-19 19:19 UTC, florianliebig commented
It's kinda an issue to use SalesChannelProduct here.

The product group selection of Add Products in Sales Channel, tries to filter products which are not yet added to the sales channel. So it normally uses the product api (using the regular product) and filtering for products NOT visible in the saleschannel.

![CleanShot 2024-10-19 at 21 19 45@2x](https://github.com/user-attachments/assets/f485e702-563b-403c-9cde-a59325feca47)


https://github.com/shopware/shopware/blob/d9f22783c794eec466ab8fbcfba4a6185300e9f5/src/Core/Content/Product/SalesChannel/SalesChannelProductDefinition.php#L45

The SalesChannelProduct always adds a visibility filter to the criteria when using the SalesChannelProductRepository, making it hard to create the desired query for the products NOT visible in the saleschannel.

2025-02-06 04:59 UTC, vienthuong commented on src/Administration/Resources/app/administration/src/module/sw-sales-channel/component/sw-sales-channel-products-assignment-dynamic-product-groups/index.js
> +                return this.getProductStreamFilter(id).then(() => this.getProducts(id));
getProducts method doesn't have id argument

2025-02-06 08:28 UTC, vienthuong approved these changes

2025-02-07 13:20 UTC, florianliebig commented on src/Administration/Resources/app/administration/src/module/sw-sales-channel/component/sw-sales-channel-products-assignment-dynamic-product-groups/index.js
> +                return this.getProductStreamFilter(id).then(() => this.getProducts(id));
Adjusted / removed

2025-02-12 07:57 UTC, vienthuong commented
Hi @florianliebig 
Could you resolve the conflict?

2025-02-12 09:48 UTC, florianliebig commented
Resolved @vienthuong

2025-04-24 07:55 UTC, mitelg requested changes
hey @florianliebig 
could you please add some tests for the lines of codes you changed?

2025-06-08 17:45 UTC, closed without merging