Added extension point for pdf renderer
shopware/platform pull request #5334
Opened 2024-10-30 08:43 UTC by OliverSkroblin

In some cases, you may want to handle the PDF rendering yourself or perform additional actions on the rendered PDF before it’s written to the file system.

Of course, you could intervene after the entire PDF rendering process, but in this case, you would need to interfere more deeply in the overall process, as you would have to read the PDF back from the system and write it again, which is not trivial.

2024-10-30 09:07 UTC, mitelg commented on src/Core/Checkout/Document/Extension/PdfRendererExtension.php
> +    public function __construct(RenderedDocument $document) {}
I guess there is a visibility missing.

2024-10-30 09:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=5334) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=5334) before we can accept your contribution.<br/><hr/>**Oliver Skroblin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=5334) it.</sub>

2024-10-31 08:37 UTC, mstegmeyer requested changes
You didn't write tests, which I can understand and accept ;) But: at least adjust the constructor you changed in the existing tests.

2024-10-31 08:37 UTC, mstegmeyer commented on src/Core/Checkout/Document/Extension/PdfRendererExtension.php
> +final class PdfRendererExtension extends Extension
since the new Extension system is still flagged as experimental, could you do it here as well?
```
 * @experimental stableVersion:v6.7.0 feature:EXTENSION_SYSTEM
```

2024-10-31 08:37 UTC, mstegmeyer commented on src/Core/Checkout/Document/Service/PdfRenderer.php
> +    public function _render(RenderedDocument $document): string
shouldn't this be private now? Otherwise, decoration pattern is broken. And should anyone be able to call this function without the ExtensionSystem?

2024-10-31 10:15 UTC, mitelg commented on src/Core/Checkout/Document/Service/PdfRenderer.php
> +    public function _render(RenderedDocument $document): string
yeah, this should be private. and it would be nice, if you could move it up above the two other private methods, so the git change is reduced :grin:

2024-11-07 10:13 UTC, closed without merging

2024-11-07 10:14 UTC, mstegmeyer commented
Done 🎉 see you in your next PR 👋