Add mapping entities
shopware/platform pull request #5364
Opened 2024-11-01 01:28 UTC by JoshuaBehrens

### 1. Why is this change necessary?

* PHPStan is annoyed, that you have to pass an entity collection but you have none, because searching is not a thing
* Searching should be a thing to get multiple many to many associations at once
* Did you have a look at the docs? It is super annoying to read and write. Just let us to read and write like other entities
* You already do that for mail_template_media which should be super weird because mapping definitions with more than two FKs as `\Shopware\Core\Framework\DataAbstractionLayer\Write\WriteCommandExtractor::extract` will decide to go for a `REPLACE INTO` approach and therefore writing this entity is already a weird case. Just make it a normal entity like product_media and product_visibility

I am happy to rewrite docs but maybe this needs to mature in a discussion.

### 2. What does this change do, exactly?

It adds a unique identifier calculation so one can use collections. This should be enough to work with as the collection can now hold all of them as expected

### 3. Describe each step to reproduce the issue or behaviour.

1. Add StoreAPI to link two entities
2. Add EntityRepository of the mapping to create or delete
3. Have phpstan set up
<img width="678" alt="PHPStan alarms about a missing type hint about a generic reference to a TCollection" src="https://github.com/user-attachments/assets/e8c7dd07-2cd2-4277-810a-af064edd5cee">

---

1. Read the docs how to write associations
2. See code, that I need to have the product repository to add an association to a tag
3. See code, that I need the mapping repository to delete the association to a tag
4. See code, that I need the product repository, to query for associations to a tag
<img width="747" alt="Same list but with an headache picture" src="https://github.com/user-attachments/assets/b4ffa10d-3d8d-4db6-a9a4-adc91c16791b">

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

2024-11-06 08:32 UTC, keulinho commented
Hey @JoshuaBehrens 

first of all thx for the contribution! 🎉 
we quickly discussed this and actually agree with you that the current handling for the mapping "entities" is a bit weird and could be simplified. 

But we definitely should add some integration testcases for mapping entities then to the `EntityRepositoryTestCase`

I'm also wondering if this is really everything there is to it, I quickly checked for `instanceof` checks for MappingEntities and guess that some (or even most of them) can and should get removed as well to really treat mapping entities as closely as possible to real entities (if you read them over the repo directly)

Because the thing we definitely wanna keep is that when you read them over e.g. the product repo directly you get product.tags directly and there the "mapping" info we need on the DB layer will be "flattened" -> to double check the changes you want to do only should have an affect when you use the "mappingRepository" directly right?

2024-11-07 12:35 UTC, JoshuaBehrens commented
@keulinho indeed. I do not try to reinvent mappings. ManyToMany associations should still be able to directly fetch the data, you can still just do REPLACE INTO to create entries. It should IMHO be forbidden to have more than two associations therefore. Maybe one wants to approach this. Then the mail_template_media thingy would not exist. I just want phpstan to be less annoying and the documentation not contain a code snippet with the hint in the prosa saying "the following should not work". This does not feel polished at that point.

Any test cases I should especially look into? Something that is important to you regarding that, that might not yet be covered by a test?

2024-11-11 08:06 UTC, keulinho commented
@JoshuaBehrens i would check reading & hydrating as well as writing  mapping entities work as expected

2025-01-14 14:11 UTC, keulinho commented on tests/integration/Core/Framework/DataAbstractionLayer/EntityRepositoryTest.php
> +            static::assertInstanceOf(MappingEntity::class, $mappedEntity);
Not needed as phpstan can already understand that ;)

2025-01-14 14:28 UTC, keulinho requested changes
Thanks for the update, in general the change looks good -> let's get that in 🚀 

However could you also add a simple test case (just write and then read a mapping entity) to the `\Shopware\Tests\Integration\Core\Framework\Api\Controller\ApiControllerTest` -> that way we can ensure that it actually works over API as well and there are no hidden surprises e.g. in the API encoding

2025-01-14 14:28 UTC, keulinho commented on tests/integration/Core/Framework/DataAbstractionLayer/EntityRepositoryTest.php
> +            $matches[] = [
I would expect that we generate the uniqueIdentifier here for each entity and compare that with $key and $entity->getUniqueIdentifier to have that covered explicitly as well 

Because right now the test does not guarantee that the uniqueIdentifier we generate in the mapping entity stays consistent

```php
$expectedKey = sprintf("categoryId-%s-productId-%s", $mappedEntity->get('categoryId'), $mappedEntity->get('productId);

static::assertEquals($key, $expectedKey);
static::assertEquals($mappedEntity->getUniqueIdentifier(), $expectedKey);
```

then we can also hard code the expected unique identifiers we expect to have in the result and do a comparison directly on the array keys after the loop
```php
static::assertEqualsCanonicalizing([
           sprintf("categoryId-%s-productId-%s", $ids->get('c2'), $ids->get('p1), // product repository create
           ...
        ], array_keys($mappedEntities));
  ```
  
  Does that make sense?

2025-01-14 15:53 UTC, keulinho commented
Somehow this change fucks up the integration tests 🤔 can you look into that?

2025-01-15 16:00 UTC, JoshuaBehrens commented
> Somehow this change mess up the integration tests 🤔 can you look into that?

I am aware of that. This is the point why I did not hand it over to you ^^' as I was not yet able to fix this

2025-02-19 08:38 UTC, keulinho commented
Hey @JoshuaBehrens to clean up a bit I would like to close this PR for now as there was not much activity in the last weeks. When you continue with this or have any other open questions feel free to reopen the PR or reach out to me :v:

2025-02-19 08:39 UTC, closed without merging