NEXT-00000 - Add state machine settings module
shopware/platform pull request #5634
Opened 2024-11-21 01:34 UTC by lacknere

### 1. Why is this change necessary?
Currently it is not possible to edit any state machine or state machine state names nor translating them into any other language. State translations are used in storefront, email templates, etc.

### 2. What does this change do, exactly?
* Added module `sw-settings-state-machine` with routes `sw.settings.state.machine.index` and `sw.settings.state.machine.detail`.
* Added state machine settings components:
    - `sw-settings-state-machine-list`
    - `sw-settings-state-machine-detail`
    - `sw-settings-state-machine-state-list`
    - `sw-settings-state-machine-state-detail`

_I've decided to not add any twig blocks because you might not want these components to be extendable. If you do, I am happy to add them._

### 3. Describe each step to reproduce the issue or behaviour.
Try translating a state machine state via Administration 🙂 

### 4. Please link to the relevant issues (if any).
#1690 
[Forum](https://forum.shopware.com/t/uebersetzungen-fuer-order-statemachinestate-translated-name/101295)
[Forum](https://forum.shopware.com/t/uebersetzungen-fuer-bestellstatus/89299)

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

2025-02-10 10:30 UTC, Bird87ZA commented
@lacknere apologies for only responding on this now, I'm not sure why I missed it.

Could you resolve the conflict and push again so I can get this through review.

2025-02-11 10:21 UTC, lacknere commented
@Bird87ZA no worries 🙂 conflict resolved, lint & jest errors fixed

2025-02-11 12:53 UTC, lernhart approved these changes
@lacknere great work! Just checked it out and feels like a great addition.

Thank you for your great PR :tada:

2025-02-11 13:15 UTC, Bird87ZA requested changes

2025-02-11 13:15 UTC, Bird87ZA commented on src/Administration/Resources/app/administration/src/module/sw-settings-state-machine/component/sw-settings-state-machine-state-list/sw-settings-state-machine-state-list.html.twig
Same comment as above with the blocks

2025-02-11 13:15 UTC, Bird87ZA commented on src/Administration/Resources/app/administration/src/module/sw-settings-state-machine/component/sw-settings-state-machine-state-detail/sw-settings-state-machine-state-detail.html.twig
I'd like to see more blocks here for extending

2025-02-11 13:15 UTC, Bird87ZA commented on src/Administration/Resources/app/administration/src/module/sw-settings-state-machine/page/sw-settings-state-machine-detail/sw-settings-state-machine-detail.html.twig
Again the comment around blocks here too

2025-02-11 13:15 UTC, Bird87ZA commented on src/Administration/Resources/app/administration/src/module/sw-settings-state-machine/page/sw-settings-state-machine-list/sw-settings-state-machine-list.html.twig
same as above

2025-02-11 13:16 UTC, Bird87ZA commented on src/Administration/Resources/app/administration/src/module/sw-settings-state-machine/component/sw-settings-state-machine-state-list/sw-settings-state-machine-state-list.html.twig
Thank you Github. This comment should have been below the comment below.

2025-02-11 14:44 UTC, cyl3x approved these changes

2025-02-11 14:44 UTC, cyl3x commented on src/Administration/Resources/app/administration/src/module/sw-settings-state-machine/index.js
> +/* eslint-disable max-len, sw-deprecation-rules/private-feature-declarations */
Not sure why you disabled `max-len` if you do line breaks anyway

2025-02-12 08:27 UTC, Bird87ZA approved these changes

2025-02-12 10:57 UTC, merged

2025-02-12 10:59 UTC, Bird87ZA commented
Thanks for your contribution @lacknere 🎉