NEXT-39787 - Google analytics tracking acceptance test
shopware/platform pull request #5851
Opened 2024-12-16 10:17 UTC by frobel

### 1. Why is this change necessary?
Extend the acceptance test suite of shopware

### 2. What does this change do, exactly?
Test the google analytics tracking option with an acceptance test

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

2024-12-16 10:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/shopware/shopware?pullRequest=5851) <br/>All committers have signed the CLA.

2024-12-16 13:22 UTC, frobel commented
@jc-sw-git I separated the tests and added one more regarding declining.

2024-12-17 03:21 UTC, vanpham-sw commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
To enhance the readability and structure of test cases, adding test.step can be a great approach. It helps to break down the test into logical, understandable steps, making it easier for others to read and maintain. It'd also be great that, people will understand what the test case is doing in detail without understanding the code.

```suggestion
    await test.step('Set system configuration to accept all cookies', async () => {
    await TestDataService.createSystemConfigEntry('core.basicInformation.acceptAllCookies', true, DefaultSalesChannel.salesChannel.id);
});

await test.step('Navigate to the homepage and verify cookie consent banner', async () => {
    await ShopCustomer.goesTo(StorefrontHome.url());
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).toBeVisible();
    await ShopCustomer.expects(StorefrontHome.consentAcceptAllCookiesButton).toBeVisible();
});

await test.step('Accept all cookies', async () => {
    await StorefrontHome.consentAcceptAllCookiesButton.click();
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.length).toEqual(2);  // Verify initial cookies
});

await test.step('Reload page and verify cookies', async () => {
    await StorefrontHome.page.reload();
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.length).toEqual(4);  // Verify cookies after reload
});

await test.step('Verify cookie consent banner is no longer visible', async () => {
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
});
```

2024-12-17 07:18 UTC, vanpham-sw commented on tests/acceptance/tests/Settings/GoogleAnalyticsAcceptTracking.spec.ts
> +    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
```suggestion
    await test.step('Set up sales channel analytics and navigate to homepage', async () => {
    const salesChannelAnalytics = await TestDataService.createSalesChannelAnalytics();
    await TestDataService.assignSalesChannelAnalytics(DefaultSalesChannel.salesChannel.id, salesChannelAnalytics.id);

    await ShopCustomer.goesTo(StorefrontHome.url());
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).toBeVisible();
});

await test.step('Configure cookie consent settings', async () => {
    await StorefrontHome.consentConfigureButton.click();
    await StorefrontHome.consentDialogStatisticsCheckbox.click();
    await StorefrontHome.consentDialogMarketingdCheckbox.click();
    await StorefrontHome.consentDialogSaveButton.click();
});

await test.step('Verify cookies are set correctly after consent', async () => {
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.find(c => c.name == 'google-analytics-enabled').value).toEqual('1');
    ShopCustomer.expects(allCookies.find(c => c.name == 'google-ads-enabled').value).toEqual('1');
    ShopCustomer.expects(allCookies.length).toEqual(5);
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
});

await test.step('Reload page and verify cookies persist', async () => {
    await StorefrontHome.page.reload();
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.find(c => c.name == 'google-analytics-enabled').value).toEqual('1');
    ShopCustomer.expects(allCookies.find(c => c.name == 'google-ads-enabled').value).toEqual('1');
    ShopCustomer.expects(allCookies.length).toEqual(5);
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
});
```

2024-12-17 07:18 UTC, vanpham-sw commented on tests/acceptance/tests/Settings/GoogleAnalyticsDeclineTracking.spec.ts
> +    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
```suggestion
    await test.step('Set up sales channel analytics and verify cookie banner', async () => {
    const salesChannelAnalytics = await TestDataService.createSalesChannelAnalytics();
    await TestDataService.assignSalesChannelAnalytics(DefaultSalesChannel.salesChannel.id, salesChannelAnalytics.id);

    await ShopCustomer.goesTo(StorefrontHome.url());
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).toBeVisible();
});

await test.step('Verify default cookie consent settings', async () => {
    await StorefrontHome.consentConfigureButton.click();
    await ShopCustomer.expects(StorefrontHome.consentDialogTechnicallyRequiredCheckbox).toBeChecked();
    await ShopCustomer.expects(StorefrontHome.consentDialogStatisticsCheckbox).not.toBeChecked();
    await ShopCustomer.expects(StorefrontHome.consentDialogMarketingdCheckbox).not.toBeChecked();
    await ShopCustomer.expects(StorefrontHome.consentDialog.getByRole('checkbox')).toHaveCount(4);
    await StorefrontHome.consentDialogSaveButton.click();
});

await test.step('Verify cookies after saving default consent settings', async () => {
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.find(c => c.name == 'google-analytics-enabled')).not.toBeDefined();
    ShopCustomer.expects(allCookies.find(c => c.name == 'google-ads-enabled')).not.toBeDefined();
    ShopCustomer.expects(allCookies.length).toEqual(3);
});

await test.step('Reload page and verify cookie persistence', async () => {
    await StorefrontHome.page.reload();
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.find(c => c.name == 'google-analytics-enabled')).not.toBeDefined();
    ShopCustomer.expects(allCookies.find(c => c.name == 'google-ads-enabled')).not.toBeDefined();
    ShopCustomer.expects(allCookies.length).toEqual(3);
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
});
```

2024-12-17 07:18 UTC, vanpham-sw commented on tests/acceptance/tests/Settings/BasicConsentBannerDeclineCookies.spec.ts
> +    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).toBeVisible();
```suggestion
    await test.step('Set system configuration and create test data', async () => {
    await TestDataService.createSystemConfigEntry('core.basicInformation.acceptAllCookies', true, DefaultSalesChannel.salesChannel.id);
    const product = await TestDataService.createBasicProduct();
    const category = await TestDataService.createCategory();
    await TestDataService.assignProductCategory(product.id, category.id);
});

await test.step('Navigate to homepage and verify cookie banner', async () => {
    await ShopCustomer.goesTo(StorefrontHome.url());
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).toBeVisible();
    await ShopCustomer.expects(StorefrontHome.consentAcceptAllCookiesButton).toBeVisible();
});

await test.step('Interact with cookie consent banner', async () => {
    await StorefrontHome.consentConfigureButton.click();
    await StorefrontHome.offcanvasBackdrop.click();
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
});

await test.step('Verify cookies after dismissing banner', async () => {
    const allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.length).toEqual(2);
});

await test.step('Navigate to product page and verify cookie banner', async () => {
    const productListItemLocators = await StorefrontHome.getListingItemByProductId(product.id);
    await productListItemLocators.productImage.click();
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).toBeVisible();
});
```

2024-12-17 07:18 UTC, vanpham-sw commented on tests/acceptance/tests/Settings/BasicConsentBannerAvailability.spec.ts
> +    let allCookies = await StorefrontHome.page.context().cookies();
can you please add test.step for other tests

```suggestion
    await test.step('Navigate to homepage and verify initial cookie banner visibility', async () => {
    await ShopCustomer.goesTo(StorefrontHome.url());
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).toBeVisible();
    await ShopCustomer.expects(StorefrontHome.consentAcceptAllCookiesButton).not.toBeVisible();
    await ShopCustomer.expects(StorefrontHome.consentOnlyTechnicallyRequiredButton).toBeVisible();
    await ShopCustomer.expects(StorefrontHome.consentConfigureButton).toBeVisible();
    await ShopCustomer.expects(StorefrontHome.consentCookiePermissionContent).toContainText(
        'This website uses cookies to ensure the best experience possible.'
    );
});

await test.step('Verify initial cookies before any consent', async () => {
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.length).toEqual(2);
});

await test.step('Configure cookie settings', async () => {
    await StorefrontHome.consentConfigureButton.click();
    await ShopCustomer.expects(StorefrontHome.consentDialogTechnicallyRequiredCheckbox).toBeChecked();
    await ShopCustomer.expects(StorefrontHome.consentDialog.getByRole('checkbox')).toHaveCount(2);
    await StorefrontHome.consentDialogSaveButton.click();
});

await test.step('Verify cookies after saving consent settings', async () => {
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.length).toEqual(3);
});

await test.step('Reload page and verify cookie persistence', async () => {
    await StorefrontHome.page.reload();
    let allCookies = await StorefrontHome.page.context().cookies();
    ShopCustomer.expects(allCookies.length).toEqual(3);
    await ShopCustomer.expects(StorefrontHome.consentCookieBannerContainer).not.toBeVisible();
});
```

2024-12-17 07:18 UTC, vanpham-sw commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +});
please format these lines

2024-12-17 12:27 UTC, vanpham-sw approved these changes

2024-12-17 14:49 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +test('As a shop customer, I want to use a accept all cookies button in the basic cookie consent banner in storefront.', { tag: '@Settings' }, async ({
```suggestion
test('As a shop customer, I want to use an "Accept All Cookies" button in the basic cookie consent banner in the storefront.', { tag: '@Settings' }, async ({
```

2024-12-17 14:52 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +    await test.step('Set system configuration to enable accept all cookies button', async () => {
```suggestion
    await test.step('Enable "Accept All Cookies" button in system configuration', async () => {
```

2024-12-17 14:54 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +    await test.step('Accept all cookies', async () => {
```suggestion
    await test.step('Click "Accept All Cookies" and verify initial cookies', async () => {
```

2024-12-17 14:55 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +    await test.step('Reload page and verify cookies', async () => {
```suggestion
    await test.step('Reload page and verify additional cookies are set', async () => {
```

2024-12-17 14:56 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +        ShopCustomer.expects(allCookies.length).toEqual(2);  // Verify initial cookies
You can remove the comment here, If you apply my test step above.

2024-12-17 14:56 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +        ShopCustomer.expects(allCookies.length).toEqual(4);  // Verify cookies after reload
You can remove the comment here, If you apply my test step above.

2024-12-17 14:58 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerAvailability.spec.ts
>  test('As a shop customer, I want use a basic cookie consent banner in storefront.', { tag: '@Settings' }, async ({
```suggestion
test('As a shop customer, I want use a basic cookie consent banner in the storefront.', { tag: '@Settings' }, async ({
```

2024-12-17 14:59 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerAvailability.spec.ts
> +    await test.step('Navigate to homepage and verify initial cookie banner visibility', async () => {
```suggestion
    await test.step('Navigate to homepage and verify initial cookie banner visibility and content', async () => {
```

2024-12-17 15:02 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerDeclineCookies.spec.ts
> +test('As a shop customer, I want to continue shopping without accepting the cookies in storefront.', { tag: '@Settings' }, async ({
```suggestion
test('As a shop customer, I want to continue shopping without accepting the cookies in the storefront.', { tag: '@Settings' }, async ({
```

2024-12-17 15:03 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerDeclineCookies.spec.ts
> +    await test.step('Interact with cookie consent banner', async () => {
```suggestion
    await test.step('Dismiss cookie banner using the configure option', async () => {
```

2024-12-17 15:04 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerDeclineCookies.spec.ts
> +    await test.step('Verify cookies after dismissing banner', async () => {
```suggestion
    await test.step('Verify cookies after dismissing the cookie banner', async () => {
```

2024-12-17 15:04 UTC, yusufttur commented on tests/acceptance/tests/Settings/BasicConsentBannerDeclineCookies.spec.ts
> +    await test.step('Navigate to product page and verify cookie banner', async () => {
```suggestion
    await test.step('Navigate to the product page and verify the cookie banner', async () => {
```

2024-12-17 15:06 UTC, yusufttur commented on tests/acceptance/tests/Settings/GoogleAnalyticsAcceptTracking.spec.ts
> +test('As a shop customer, I want to accept the Google Analytics tracking within basic cookie consent banner in storefront.', { tag: '@Settings' }, async ({
```suggestion
test('As a shop customer, I want to accept Google Analytics tracking via the basic cookie consent banner in the storefront.', { tag: '@Settings' }, async ({
```

2024-12-17 15:08 UTC, yusufttur commented on tests/acceptance/tests/Settings/GoogleAnalyticsAcceptTracking.spec.ts
> +    await test.step('Set up sales channel analytics and navigate to homepage', async () => {
```suggestion
    await test.step('Configure sales channel analytics and verify cookie banner visibility on the home page', async () => {
```

2024-12-17 15:09 UTC, yusufttur commented on tests/acceptance/tests/Settings/GoogleAnalyticsAcceptTracking.spec.ts
> +    await test.step('Configure cookie consent settings', async () => {
```suggestion
    await test.step('Enable Google Analytics and marketing tracking via cookie settings', async () => {
```

2024-12-17 15:10 UTC, yusufttur commented on tests/acceptance/tests/Settings/GoogleAnalyticsAcceptTracking.spec.ts
> +    await test.step('Verify cookies are set correctly after consent', async () => {
```suggestion
    await test.step('Verify tracking cookies are set correctly after consent', async () => {
```

2024-12-17 15:11 UTC, yusufttur commented on tests/acceptance/tests/Settings/GoogleAnalyticsAcceptTracking.spec.ts
> +    await test.step('Reload page and verify cookies persist', async () => {
```suggestion
    await test.step('Verify tracking cookies persist after page reload', async () => {
```

2024-12-17 15:11 UTC, yusufttur commented on tests/acceptance/tests/Settings/GoogleAnalyticsDeclineTracking.spec.ts
> +test('As a shop customer, I want to accept the technical required cookies without activating Google Analytics tracking within basic cookie consent banner in storefront.', { tag: '@Settings' }, async
```suggestion
test('As a shop customer, I want to accept only the technically required cookies without activating Google Analytics tracking via the basic cookie consent banner in the storefront.', { tag: '@Settings' }, async ({
```

2024-12-17 15:12 UTC, yusufttur commented on tests/acceptance/tests/Settings/GoogleAnalyticsDeclineTracking.spec.ts
> +    await test.step('Set up sales channel analytics and verify cookie banner', async () => {
```suggestion
    await test.step('Configure sales channel analytics and verify cookie banner visibility', async () => {
```

2024-12-17 15:13 UTC, yusufttur commented on tests/acceptance/tests/Settings/GoogleAnalyticsDeclineTracking.spec.ts
> +    await test.step('Reload page and verify cookie persistence', async () => {
```suggestion
    await test.step('Verify cookies persist after page reload', async () => {
```

2024-12-17 15:14 UTC, yusufttur requested changes
I suggest some changes to the descriptions and the steps to better readability.

2024-12-17 16:09 UTC, frobel commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +        ShopCustomer.expects(allCookies.length).toEqual(2);  // Verify initial cookies
```suggestion
        ShopCustomer.expects(allCookies.length).toEqual(2);
```

2024-12-17 16:09 UTC, frobel commented on tests/acceptance/tests/Settings/BasicConsentBannerAcceptAllCookies.spec.ts
> +        ShopCustomer.expects(allCookies.length).toEqual(4);  // Verify cookies after reload
```suggestion
        ShopCustomer.expects(allCookies.length).toEqual(4);
```

2024-12-17 16:13 UTC, yusufttur approved these changes

2024-12-17 16:30 UTC, GitEvil approved these changes

2024-12-17 16:36 UTC, merged