Update to doctrine/dbal 4.0
shopware/platform pull request #5861
Opened 2024-12-16 14:55 UTC by h1k3r

### 1. Why is this change necessary?

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

2024-12-16 14:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=5861) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=5861) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=5861) it.</sub>

2025-01-10 13:25 UTC, mitelg commented on src/Core/Content/Flow/Dispatching/FlowDispatcher.php
> -                if ($e->getPrevious() && $this->isInNestedTransaction()) {
is this not needed anymore? can we just remove it?

2025-01-10 13:25 UTC, mitelg commented on src/Core/Test/Stub/Doctrine/QueryBuilderDataExtractor.php
> + * @todo: throw reflection exception to call in tests and fail if dbal implementations was changed?
have to marked the tests, that needed to be refactored?

2025-01-14 13:39 UTC, h1k3r commented on src/Core/Content/Flow/Dispatching/FlowDispatcher.php
> -                if ($e->getPrevious() && $this->isInNestedTransaction()) {
If I am not mistaken, deleted code became unreachable.

FlowDispatcher::isInNestedTransaction had the next code:
```
return $this->container->get(Connection::class)->getTransactionNestingLevel() !== 1 && !$this->container->get(Connection::class)->getNestTransactionsWithSavepoints();
```
As now `Connection::getNestTransactionsWithSavepoints()` [always returns true](https://github.com/doctrine/dbal/blob/4.2.x/src/Connection.php#L999), isInNestedTransaction should always return false.

2025-01-14 13:46 UTC, mitelg commented on src/Core/Content/Flow/Dispatching/FlowDispatcher.php
> -                if ($e->getPrevious() && $this->isInNestedTransaction()) {
ah, so the whole feature was removed from DBAL? do we need some replacement then on our side?

2025-01-14 14:47 UTC, h1k3r commented on src/Core/Content/Flow/Dispatching/FlowDispatcher.php
> -                if ($e->getPrevious() && $this->isInNestedTransaction()) {
That is a very good question!

This change enables nested transaction behavior, and if rollback called in the nested transaction, only nested transaction will be rolled back. Previously whole transaction was marked for rollback. For more details see the [docs](https://www.doctrine-project.org/projects/doctrine-dbal/en/3.9/reference/transactions.html#transaction-nesting).

I believe it worth to bring it to an internal discussion.

2025-01-21 15:00 UTC, h1k3r commented on src/Core/Test/Stub/Doctrine/QueryBuilderDataExtractor.php
> + * @todo: throw reflection exception to call in tests and fail if dbal implementations was changed?
So far not. Do you have suggestions how to do it better? I did not see a lot of todos in the code so far.

2025-01-21 21:20 UTC, mitelg commented on src/Core/Test/Stub/Doctrine/QueryBuilderDataExtractor.php
> + * @todo: throw reflection exception to call in tests and fail if dbal implementations was changed?
usually we create tickets for such things

2025-01-24 10:22 UTC, h1k3r commented on src/Core/Framework/DataAbstractionLayer/Search/Parser/ParseResult.php
> +    public function addParameter(string $key, mixed $value, ParameterType|ArrayParameterType $type = ParameterType::STRING): void
QueryBuilder does not support null as default value.
We could keep here null as default type representing "no value", and in required places use something like `$query->setParameter($key, $value, $parsed->getType($key) ?? ParameterType::STRING);`

The other option is more explicit at the price of a bit more verbosity. As the class is internal, I believe it does not matter so much and can be easily changed.

Happy to discuss/change if there is another opinion.

2025-01-28 10:36 UTC, h1k3r commented on src/Core/Content/Flow/Dispatching/FlowDispatcher.php
> -                if ($e->getPrevious() && $this->isInNestedTransaction()) {
Ok, the result of the discussion that as savepoints are always enabled, error handling and transaction rollback/commit should always be done on the level of the action. So we are keeping the logic like it is now.

2025-01-28 10:37 UTC, h1k3r commented on src/Core/Test/Stub/Doctrine/QueryBuilderDataExtractor.php
> + * @todo: throw reflection exception to call in tests and fail if dbal implementations was changed?
Added comment to the ticket

2025-01-30 09:04 UTC, AydinHassan commented on src/Core/Maintenance/System/Service/ShopConfigurator.php
> +            StatementHelper::bindParameters($stmt, ['code' => 'x-' . $locale . '_tmp', 'locale_id' => $currentLocaleId]);
Why not use `StatementHelper::executeStatement()` ? Was it added later on?

2025-01-30 09:27 UTC, AydinHassan commented on src/Core/Migration/V6_4/Migration1612980753AddLinkSettingsToCategory.php
> +            ->update('category_translation translation')
That seems quite strange, is that really correct? 😱

2025-01-30 10:28 UTC, h1k3r commented on src/Core/Migration/V6_4/Migration1612980753AddLinkSettingsToCategory.php
> +            ->update('category_translation translation')
That's the way to pass alias like in this example: https://www.doctrine-project.org/projects/doctrine-dbal/en/4.2/reference/query-builder.html#set-clause
But yes, reads not nice, probably it's better either to shorten alias to one letter or avoid using alias at all.

2025-01-30 11:16 UTC, AydinHassan approved these changes

2025-01-30 11:16 UTC, AydinHassan commented on src/Core/Test/Stub/Doctrine/FakeResultFactory.php
> +class FakeResultFactory
I think we should add some tests for this

2025-01-30 11:16 UTC, AydinHassan commented on tests/unit/Core/Content/ProductStream/DataAbstractionLayer/ProductStreamIndexerTest.php
> +            ->with(static::callback(function ($key) use ($matcher, $params) {
im pretty sure you can just hint it `function ($key, $value)` and you get both key and value 🤔

2025-01-30 11:16 UTC, AydinHassan commented on src/Core/System/CustomEntity/Schema/SchemaUpdater.php
> +                    $nullable['length'] = 255;
This is a bit odd, can we just change the name of `$nullable` ? Sorry I know it's not directly related to your changes

2025-01-30 11:16 UTC, AydinHassan commented on changelog/_unreleased/2024-12-12-update-to-doctrine-dbal-4-2.md
> +* Added `Shopware\Core\Framework\DataAbstractionLayer\Util\StatementHelper` to simplify binding multiple parameters to a statement
Why did doctrine drop this? Do we recommend to keep using `StatementHelper` going forward or do we also follow doctrine there?

2025-01-30 11:17 UTC, AydinHassan commented on src/Core/Migration/V6_4/Migration1612980753AddLinkSettingsToCategory.php
> +            ->update('category_translation translation')
Ah did not notice it was alias, I actually thought it was multi table update 😄 - using `t` would would probably make it obvious but fine for me either way.

2025-01-30 17:40 UTC, h1k3r commented on changelog/_unreleased/2024-12-12-update-to-doctrine-dbal-4-2.md
> +* Added `Shopware\Core\Framework\DataAbstractionLayer\Util\StatementHelper` to simplify binding multiple parameters to a statement
I assume to make API more clean, or better enforce parameters typing. Original deprecation commit does not contain too much information. https://github.com/doctrine/dbal/commit/2c1236199247d2a0f8c27bca3cec1163c7a4c257

It's nice to have helper at least for our internal usage. I don't mind opening it to the public, as it should not add too much to maintenance work, but I am happy to hear other opinions.

2025-01-30 19:59 UTC, shyim commented on changelog/_unreleased/2024-12-12-update-to-doctrine-dbal-4-2.md
> +* Changed `Shopware\Core\Framework\DataAbstractionLayer\Dbal\Common\LastIdQuery::__construct` and `Shopware\Core\Framework\DataAbstractionLayer\Dbal\Common\OffsetQuery::__construct` to accept `Shopwa
Btw why we needed to change the QueryBuilder here. isn't the doctrine one enough? any method we call there is also available in the Doctrine one.

2025-01-31 08:08 UTC, AydinHassan commented on changelog/_unreleased/2024-12-12-update-to-doctrine-dbal-4-2.md
> +* Added `Shopware\Core\Framework\DataAbstractionLayer\Util\StatementHelper` to simplify binding multiple parameters to a statement
Fine for me 👍

2025-01-31 08:10 UTC, AydinHassan commented on changelog/_unreleased/2024-12-12-update-to-doctrine-dbal-4-2.md
> +* Changed `Shopware\Core\Framework\DataAbstractionLayer\Dbal\Common\LastIdQuery::__construct` and `Shopware\Core\Framework\DataAbstractionLayer\Dbal\Common\OffsetQuery::__construct` to accept `Shopwa
It's because of the select/order parts stuff they dropped

2025-01-31 08:17 UTC, h1k3r commented on changelog/_unreleased/2024-12-12-update-to-doctrine-dbal-4-2.md
> +* Changed `Shopware\Core\Framework\DataAbstractionLayer\Dbal\Common\LastIdQuery::__construct` and `Shopware\Core\Framework\DataAbstractionLayer\Dbal\Common\OffsetQuery::__construct` to accept `Shopwa
That's an ugly part of this PR. In few places we use Doctrine's `QueryBuilder` as an object to transfer request data. For example `LastIdQuery`, `OffsetQuery` and `FilterTagIdsService` are using `QueryBuilder::getSelectParts`, and `EntityReader` is using `QueryBuilder::getOrderByParts`. Those used methods were removed in the version 4.0 of doctrine/dbal.

We considered two options, either to introduce internal object to carry the query information trough different parts of dal instead of QueryBuilder, or reimplement two of those methods in the `Shopware\Core\Framework\DataAbstractionLayer\Dbal\QueryBuilder`, and chosen the second one.

2025-01-31 09:11 UTC, mitelg requested changes

2025-01-31 09:11 UTC, mitelg commented on changelog/_unreleased/2024-12-12-update-to-doctrine-dbal-4-2.md
> +# Next Major Version Changes
this will be merged after the split off of 6.6 from trunk right? so this section will be merged into the 6.8 upgrade guide :wink: 

so this should be like this. 
```suggestion
# # Upgrade Information
```

additionally I guess it would make sense, to alredy add this to the curated 6.7 upgrade guide

2025-01-31 09:11 UTC, mitelg commented on src/Core/Checkout/Customer/DataAbstractionLayer/CustomerWishlistProductExceptionHandler.php
> +    public function matchException(\Throwable $e): ?\Exception
should we also change the return type? :thinking:

2025-01-31 09:11 UTC, mitelg commented on src/Core/Framework/DataAbstractionLayer/Util/StatementHelper.php
> +class StatementHelper
should we make it final?

2025-01-31 09:11 UTC, mitelg commented on src/Core/Framework/DataAbstractionLayer/Util/StatementHelper.php
> +class StatementHelper
maybe a dumb question, but why is that needed? couldn't we use the methods that are provided by `\Doctrine\DBAL\Connection` directly, instead of handling with `Statement`s?

2025-01-31 09:11 UTC, mitelg commented on src/Core/Migration/V6_4/Migration1612980753AddLinkSettingsToCategory.php
> +            ->update('category_translation translation')
sometimes I see `ct` as alias in such cases. I personally try to avoid them, as I think, they do not really help regarding readability

2025-01-31 09:11 UTC, mitelg commented on src/Core/System/CustomEntity/Schema/CustomEntitySchemaUpdater.php
> +            //            $fks = $table->getForeignKeys();
can this be deleted?

2025-01-31 09:11 UTC, mitelg commented on src/Core/System/CustomEntity/Schema/SchemaUpdater.php
> +                    $nullable['length'] = 255;
yeah the variable name is misleading

2025-01-31 09:11 UTC, mitelg commented on tests/unit/Core/Content/Rule/DataAbstractionLayer/RuleAreaUpdaterTest.php
> +                self::assertEquals($params[$matcher->numberOfInvocations() - 1][0], $key);
please use `assertSame` where possible instead, as it is type safe

2025-01-31 09:43 UTC, h1k3r commented on src/Core/Framework/DataAbstractionLayer/Util/StatementHelper.php
> +class StatementHelper
It would be possible for the cases where statement is not reused, as Connection::executeStatement and Connection::executeQuery are accepting string sql and prepare statement under the hood.

For the cases where statement is used for multiple queries, it would be nice to use Connection::bindParameters, but unfortunately it's private.

Do you want me to refactor all the cases where statement is used only once?

2025-01-31 10:00 UTC, mitelg commented on src/Core/Framework/DataAbstractionLayer/Util/StatementHelper.php
> +class StatementHelper
no, that would be optional for me, it would just to be consistent :blush: 

I didn't thought about reusing the statement :+1:

2025-01-31 10:02 UTC, h1k3r commented on src/Core/Framework/DataAbstractionLayer/Util/StatementHelper.php
> +class StatementHelper
Done

2025-01-31 10:12 UTC, h1k3r commented on src/Core/System/CustomEntity/Schema/SchemaUpdater.php
> +                    $nullable['length'] = 255;
renamed to `$fieldOptions`

2025-01-31 10:14 UTC, h1k3r commented on tests/unit/Core/Content/ProductStream/DataAbstractionLayer/ProductStreamIndexerTest.php
> +            ->with(static::callback(function ($key) use ($matcher, $params) {
Yep, if use willReturnCallback, fixed

2025-01-31 12:07 UTC, h1k3r commented on src/Core/Maintenance/System/Service/ShopConfigurator.php
> +            StatementHelper::bindParameters($stmt, ['code' => 'x-' . $locale . '_tmp', 'locale_id' => $currentLocaleId]);
Yep, it was added later. Replaced all bindParameters usages.

2025-01-31 12:13 UTC, h1k3r commented on src/Core/Checkout/Customer/DataAbstractionLayer/CustomerWishlistProductExceptionHandler.php
> +    public function matchException(\Throwable $e): ?\Exception
Good question.
I like to return more concrete types, while depend on the abstract ones, but handlers are public. So probably it's better to change return type to more generic not to cause breaks in the future.

The other question could be if we should keep handlers public or internalize them.

2025-01-31 12:34 UTC, mitelg approved these changes

2025-01-31 12:36 UTC, mitelg commented on src/Core/Checkout/Customer/DataAbstractionLayer/CustomerWishlistProductExceptionHandler.php
> +    public function matchException(\Throwable $e): ?\Exception
I guess, we can make them internal, but that is maybe something for another task. 

everybody can build their own handlers, so no need to extend ours

2025-02-06 16:16 UTC, merged