Next 19776/make selection of addresses more handy
shopware/platform pull request #5874
Opened 2024-12-17 11:21 UTC by FlorianKe

2024-12-18 09:35 UTC, cyl3x requested changes
Your twig files should have more blocks so everyone is able to modify it more. Also please check your formatting, as indentation isn't consistent.

2024-12-18 09:35 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/main.js
> +PluginManager.register('NewAddressEditor', () => import('src/plugin/new-address-editor/new-address-editor.plugin'), '[data-new-address-editor]');
Rename your plugin to `AddressManager`

2024-12-18 09:35 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/scss/component/_new-address-editor.scss
> +}
scope to `address-manager-modal` only

2024-12-18 09:35 UTC, cyl3x commented on src/Storefront/Resources/snippet/de_DE/storefront.de-DE.json
> +    "CHECKOUT__CUSTOMER_ADDRESS_IS_ACTIVE": "Dumm oder so?"
```suggestion
    "CHECKOUT__CUSTOMER_ADDRESS_IS_ACTIVE": "Die aktive Adresse kann nicht gelöscht werden"
```

2024-12-18 09:35 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/component/address/address-manager-account-list.html.twig
> +    {% if (context.customer.activeShippingAddress.id != address.id) or (context.customer.activeBillingAddress.id != address.id)%}
```suggestion
    {% if (context.customer.activeShippingAddress.id != address.id) or (context.customer.activeBillingAddress.id != address.id) %}
```

2024-12-18 09:35 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/component/address/address-manager-address-list.html.twig
> +    {% set type = '' %}
why this fallback? If done, shouldn't it fall back to a valid type?

2024-12-23 13:10 UTC, FlorianKe commented on src/Storefront/Resources/public/static/js/draco/README.md
remove file

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-editor/address-editor.plugin.js
> + * @deprecated tag:v6.7.0 - will be removed use new-address-editor plugin
```suggestion
 * @deprecated tag:v6.7.0 - will be removed, use address-manager plugin instead
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        billingTabPaneId: 'billing-address-tab-pane',
```suggestion
        shippingAddressTabSelector: '#shipping-address-tab',
        billingAddressTabSelector: '#billing-address-tab',
        shippingTabPaneSelector: '#shipping-address-tab-pane',
        billingTabPaneSelector: '#billing-address-tab-pane',
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        this.el.addEventListener('click', onClick);
not really necessary to dedupe
```suggestion
        this.el.removeEventListener('click', this._getModal.bind(this));
        this.el.addEventListener('click', this._getModal.bind(this));
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            (response)  => {
```suggestion
            (response) => {
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            console.warn('[AddressManagerPlugin] Invalid HTML element provided.');
What? where? how? if you're logging something in stringified content, you need to know what it's about.

Besides that, your code flow willl never end in this situation, as it gets created from `querySelectorAll`, therefore remove it and use a doc type instead:

```js
/**
  * @param {HTMLElement} element
 */
_onSetRadioInputActive(element, event){
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            console.warn('[AddressManagerPlugin] Element has not the right dataset');
Something like:
```suggestion
            console.warn('[AddressManagerPlugin] Radio input is missing id or address type');
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            console.warn('[AddressManagerPlugin] Element has not the right dataset');
s.a.

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            console.warn('[AddressManagerPlugin] Element is missing id or type attribute');
```suggestion
            console.warn('[AddressManagerPlugin] Default buttion is missing address id or type attribute');
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-search/address-search.plugin.js
> +            }
This might be a cleaner solution and more in line with other plugins:
```suggestion
            if (text.includes(searchQuery)) {
                item.classList.remove('d-none')
            } else {
                item.classList.add('d-none')
            }
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/snippet/de_DE/storefront.de-DE.json
> +    "addressSaveAndUse": "Speicher und verwenden",
```suggestion
    "addressSaveAndUse": "Speichern und verwenden",
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/snippet/de_DE/storefront.de-DE.json
> +    "noAvailableAddresses": "Keine Adressen zur Auswahl",
```suggestion
    "noAvailableAddresses": "Keine Adressen verfügbar",
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/component/address/address-editor-modal.html.twig
The rest of the file is pretty hard to read. As far as I can tell, only the formatting has changed, so I think it would be best if you changed it back and don't touch it.

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/component/address/address-manager-item.html.twig
> +                                <li><a class="dropdown-item text-primary address-manager-modal-address-form" href="#" data-address-id="{{ address.id }}" data-address-type="{{ type }}">{{ 'global.defa
this attribute list is long enough to have some line breaks:
```suggestion
                                <li>
                                    <a
                                        class="dropdown-item text-primary address-manager-modal-address-form"
                                        href="#"
                                        data-address-id="{{ address.id }}"
                                        data-address-type="{{ type }}"
                                    >
                                        {{ 'global.default.edit'|trans|sw_sanitize }}
                                    </a>
                                </li>
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/component/address/address-manager-item.html.twig
> +                                        <a class="dropdown-item address-manager-modal-set-default-address" href="#" data-address-id="{{ address.id }}" data-address-type="{{ type }}">
s.a.

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/component/address/address-manager-modal-create-address.html.twig
> +                  data-form-validation="true">
```suggestion
            <form
                method="post"
                action="{{ url('frontend.account.addressmanager', { addressId: postedAddress.id, type }) }}"
                id="address-manager-modal-address-form"
                data-form-validation="true"
            >
```

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/component/address/address-manager-modal-create-address.html.twig
> +                    title="{{ 'account.addressSaveChange'|trans|striptags }}">
s.a.

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/component/address/address-manager-modal.html.twig
> +                           checked>
Please check all elements here and correct formatting of line breaks in attributes.

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Resources/views/storefront/page/account/addressbook/address-item.html.twig
Add some more twig blocks to this file

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Controller/AddressController.php
> +            dump($e->getMessage());
please remove this

2025-01-06 10:49 UTC, cyl3x commented on src/Storefront/Controller/AddressController.php
> +        return new RedirectResponse($this->generateUrl('frontend.account.address.page', ['addressDeleted' => $success]));
is `addressDeleted` used for something else? how about adding a flash about the success/failure of the deletion like in your other methods?

2025-01-08 15:12 UTC, mitelg requested changes

2025-01-08 15:12 UTC, mitelg commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +## Breaking Change 1:
please remember this will exactly copied like this to the upgrade guide. you should find meaningful topics instead

2025-01-08 15:12 UTC, mitelg commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +* Added `src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js`
imo it does not make sense to just list a bunch of new added files. You should write down, what is essential for external and/or internal developers to know. what can they do now? what things changed? 

I can see from the commit what files are new, I do not need a list here for what :slightly_smiling_face:

2025-01-08 15:12 UTC, mitelg commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +* Changed `src/Core/Framework/Resources/config/packages/feature.yaml` and added feature flag
which one was added and with what purpose?

2025-01-08 15:12 UTC, mitelg commented on src/Storefront/Controller/AddressController.php
> +            // @phpstan-ignore-next-line
why is that needed?

2025-01-08 15:12 UTC, mitelg commented on src/Storefront/Controller/AddressController.php
> +    * @deprecated tag:v6.7.0 - will be removed
is there an alternative? why is PHPStan not complaining that a `Feature::triggerDeprecationOrThrow` is missing? :sweat_smile:

2025-01-08 15:12 UTC, mitelg commented on src/Storefront/Controller/AddressController.php
> +        } catch (\Exception) {
should we catch `Throwable` instead?

2025-01-08 15:12 UTC, mitelg commented on src/Storefront/Controller/AddressController.php
> +            // @phpstan-ignore-next-line
why does it need to be ignored?

2025-01-08 15:12 UTC, mitelg commented on src/Storefront/Controller/AddressController.php
> +            // @phpstan-ignore-next-line
what needs to be ignored here?

2025-01-08 15:12 UTC, mitelg commented on src/Storefront/Resources/app/storefront/src/scss/component/_address-manager.scss
> +        color: #FFFFFF;
I am not the frontend pro, but don't we have predefined color variables, which we should use?

2025-01-08 15:12 UTC, mitelg commented on src/Storefront/Resources/app/storefront/src/scss/component/_address-manager.scss
> +    padding-bottom: 0;
why not using the bootstrap classes for such cases?

2025-01-08 15:12 UTC, mitelg commented on src/Storefront/Resources/views/storefront/component/address/address-editor-modal.html.twig
> +{# @deprecated tag:v6.7.0 - File will be removed as it is no longer loaded by default. #}
make sure that you also deprecate all child template files which are used only here. otherwise we would have orphan templates lying around with no use

2025-01-13 08:45 UTC, FlorianKe commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +* Changed `src/Core/Framework/Resources/config/packages/feature.yaml` and added feature flag
Before I change the line, the feature name is `FEATURE_NEXT_19776`, should we change the name or its fine?

2025-01-13 08:54 UTC, mitelg commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +* Changed `src/Core/Framework/Resources/config/packages/feature.yaml` and added feature flag
I don't care about the name, but it should be mentioned here, and what I can enable with it, so people know, what it is about

2025-01-13 10:11 UTC, mitelg commented on src/Storefront/Controller/AddressController.php
> +        Feature::triggerDeprecationOrThrow('v6.7.0.0', 'Method `AddressController::addressBook` will be removed, use `AddressController::addressManager` instead');
```suggestion
        Feature::triggerDeprecationOrThrow(
            'v6.7.0.0',
            Feature::deprecatedMethodMessage(
            __CLASS__,
            __METHOD__,
            'v6.7.0.0',
            'AddressController::addressManager'
            )
        );
```

2025-01-13 10:11 UTC, mitelg commented on src/Storefront/Controller/AddressController.php
> +    * @deprecated tag:v6.7.0 - will be removed
```suggestion
    * @deprecated tag:v6.7.0 - Will be removed. Use `AddressController::addressManager` instead
```

2025-01-13 10:11 UTC, mitelg commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +* Changed `src/Storefront/Controller/AddressController.php` and added new routes `AddressController::addressManager`, `AddressController::addressManagerGet` and `AddressController::addressManagerSwit
Additionally to "Core", we also have a headline for "API", where you could also state, what the route names are and what they are used for

2025-01-13 12:55 UTC, mitelg approved these changes

2025-01-14 20:15 UTC, mstegmeyer requested changes

2025-01-14 20:15 UTC, mstegmeyer commented on src/Core/Framework/Resources/config/packages/feature.yaml
> +        toggleable: false
Can you rename the feature flag? We don't really do the `FEATURE_NEXT_*` anymore, I suggest `ADDRESS_SELECTION_REWORK`.
Also, I would vote for this being toggleable, then it also needs a description, e.g. `Improved and redesigned management of customer addresses in the Storefront`

2025-01-14 20:15 UTC, mstegmeyer commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        const pseudoModal = new PseudoModalUtil(response,);
I assume, this comma is not necessary?

2025-01-14 20:15 UTC, mstegmeyer commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        modal.children[0].classList.add('modal-dialog-address');
can we put this into options? an array of classes to add?

2025-01-14 20:15 UTC, mstegmeyer commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        document.querySelector(this.options.shippingTabPaneSelector).classList.add('active');
could we simplify this? And also declare the relevant classes in options? Or maybe even combine `show` and `active` into one class?

2025-01-14 20:15 UTC, mstegmeyer commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        if (event.target.closest('.dropdown')) {
again, please into options.

2025-01-14 20:15 UTC, mstegmeyer commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            '/account/address/switch',
all URLs in Storefront plugins need to be injected via options. This way doesn't work with shops hosted in non-root directories (e.g. `https://shopware.com/shop/`)

2025-01-14 20:15 UTC, mstegmeyer commented on src/Storefront/Resources/snippet/de_DE/storefront.de-DE.json
> +    "addressNotFound": "Keine Adresse gefunden",
This snippet is not used. Was this supposed to be an empty-state for the search? I would appreciate that instead of just showing nothing

2025-01-15 10:53 UTC, Bird87ZA commented on src/Core/Framework/Resources/config/packages/feature.yaml
> +        toggleable: false
agree with this

2025-01-16 07:59 UTC, FlorianKe commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        document.querySelector(this.options.shippingTabPaneSelector).classList.add('active');
We need `show` and `active` and I would not combine these classes because they are default bootstrap classes.

2025-01-16 10:01 UTC, mstegmeyer commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        document.querySelector(this.options.shippingTabPaneSelector).classList.add('active');
alright, then we keep both classes, it just seemed very long and duplicated and you do `querySelector` searches for the same selector multiple times. Your opinion, @cyl3x ?

2025-01-23 15:27 UTC, lernhart requested changes, later dismissed

2025-01-23 15:27 UTC, lernhart commented on src/Storefront/Controller/AddressController.php
> +        $params = [];
This seems unnecessary

Update it to provide $viewData->getVars() in ->renderStorefront()

2025-01-23 15:27 UTC, lernhart commented on src/Storefront/Controller/AddressController.php
> +    public function addressManager(Request $request, RequestDataBag $dataBag, SalesChannelContext $context, CustomerEntity $customer, ?string $addressId, #[MapQueryParameter] ?string $type = null): R
```suggestion
    public function addressManager(Request $request, RequestDataBag $dataBag, SalesChannelContext $context, CustomerEntity $customer, ?string $addressId = null, #[MapQueryParameter] ?string $type = null): Response
```

2025-01-23 15:27 UTC, lernhart commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +                }
```suggestion
                if (response.status === 204) {
                    return location.reload();
                }
                
                this._replaceModalContent(data);
```

2025-01-23 15:27 UTC, lernhart commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        }
```suggestion
        type === SHIPPING
            ? document.querySelector(this.options.currentShippingIdSelector).value = id
            : document.querySelector(this.options.currentBillingIdSelector).value = id;
```

2025-01-23 15:27 UTC, lernhart commented on src/Storefront/Resources/app/storefront/src/plugin/address-search/address-search.plugin.js
> +            }
```suggestion
            text.includes(searchQuery)
                ? item.classList.remove('d-none')
                : item.classList.add('d-none');
```

2025-01-23 15:27 UTC, lernhart commented on src/Storefront/Resources/app/storefront/src/plugin/address-search/address-search.plugin.js
> +        }
```suggestion
        searchQuery.length === 0
            ? empty.classList.remove('d-none')
            : notFound.classList.remove('d-none');
```

2025-01-24 07:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            console.warn('[AddressManagerPlugin] Unable to create loading indicator on button', error);
do you really run into this case?

2025-01-24 07:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
please try to add jsdoc types to all functions here

2025-01-24 07:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        if (event.target.closest('.dropdown')) {
Please add a comment here, so everyone understands why this early return is necessary

2025-01-24 07:49 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +        document.querySelector(this.options.shippingTabPaneSelector).classList.add('active');
```suggestion
    _onSwitchToBillingTab() {
        document.querySelector(this.options.billingAddressTabSelector).checked = true;
        document.querySelector(this.options.shippingTabPaneSelector).classList.remove('show', 'active');
        document.querySelector(this.options.billingTabPaneSelector).classList.add('show', 'active');
    }

    _onSwitchToShippingTab() {
        document.querySelector(this.options.shippingAddressTabSelector).checked = true;
        document.querySelector(this.options.billingTabPaneSelector).classList.remove('show', 'active');
        document.querySelector(this.options.shippingTabPaneSelector).classList.add('show', 'active');
```

2025-01-24 11:40 UTC, cyl3x commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +## Deprecated old address   editor
```suggestion
## Deprecated old address editor
```

2025-01-24 11:40 UTC, cyl3x commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +
please also include information about the deprecated and added js plugins

2025-01-24 11:40 UTC, cyl3x commented on src/Storefront/Controller/AddressController.php
> +    public function addressManagerGet(Request $request, SalesChannelContext $context, CustomerEntity $customer): Response
```suggestion
    #[Route(path: '/widgets/account/address-manager', name: 'frontend.account.addressmanager', options: ['seo' => true], defaults: ['XmlHttpRequest' => true, '_loginRequired' => true, '_loginRequiredAllowGuest' => true], methods: ['GET'])]
    public function addressManager(Request $request, SalesChannelContext $context, CustomerEntity $customer): Response
```

2025-01-24 11:40 UTC, cyl3x commented on src/Storefront/Controller/AddressController.php
> +    public function addressManager(Request $request, RequestDataBag $dataBag, SalesChannelContext $context, CustomerEntity $customer, ?string $addressId = null, #[MapQueryParameter] ?string $type = n
```suggestion
    #[Route(path: '/widgets/account/address-manager/{addressId?}', name: 'frontend.account.addressmanager.upsert', options: ['seo' => true], defaults: ['XmlHttpRequest' => true, '_loginRequired' => true, '_loginRequiredAllowGuest' => true], methods: ['POST'])]
    public function addressManagerUpsert(Request $request, RequestDataBag $dataBag, SalesChannelContext $context, CustomerEntity $customer, ?string $addressId = null, #[MapQueryParameter] ?string $type = null): Response
```

2025-01-24 11:40 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +     * registers all needed event listeners
```suggestion
     * Registers all needed event listeners for interacting with the modal.
     * Needs to be run every time the modal gets replaced.
```

2025-01-24 11:40 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +    _getModal(event) {
```suggestion
    /**
     * Initially get the modal.
     *
     * @private
     * @param {PointerEvent} event
     */
    _getModal(event) {
```

2025-01-24 11:40 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +    _renderModal(response) {
```suggestion
    /**
     * Initially renders the modal.
     *
     * @param {String} response
     */
    _renderModal(response) {
```

2025-01-24 11:40 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +    _onSaveChanges(event) {
```suggestion
    /**
     * ...
     */
    _onSaveChanges(event) {
```

2025-01-24 11:40 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/test/plugin/address-manager/address-manager.plugin.test.js
> +        create();
Do not use a test case persistent variable for a value that shouldn't persist that long
```suggestion
describe('AddressManagerPlugin test', () => {
    let addressManager;

    afterEach(() => {
        document.body.innerHTML = '';
        jest.useRealTimers();
    });

    test('plugin initializes', () => {
        addressManager = create();
```

2025-01-24 11:40 UTC, cyl3x commented on src/Storefront/Resources/app/storefront/test/plugin/address-serach/address-search.plugin.test.js
> +let addressSearch;
s.a.

2025-01-24 13:24 UTC, Bird87ZA submitted a review, later dismissed

2025-01-24 13:24 UTC, Bird87ZA commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            console.warn(`[AddressManagerPlugin] options.initialTab was expected to be 'billing' or 'shipping', got '${this.options.initialTab}'`);
What is the rule around using `console.warn`? Is it allowed in production, or was this just leftover from debugging?

(off topic: based on our Thursday `dd` discussion, one can never be to sure)

2025-01-24 13:24 UTC, Bird87ZA commented on changelog/_unreleased/2024-11-28-new-adresse-selection-modal.md
> +* Added `FEATURE_NEXT_19776` feature flag to enable/disable the new address manager modal and account address page redesign
Is this the standard for feature flags? To use the ticket number? If not, then I'd rather make it something like `FEATURE_IMPROVED_ADDRESS_MODAL`

2025-01-24 13:24 UTC, Bird87ZA commented on src/Core/Framework/Resources/config/packages/feature.yaml
> +        toggleable: false
Ah I see here it was commented too.

2025-01-24 13:24 UTC, Bird87ZA commented on src/Storefront/Resources/snippet/en_GB/storefront.en-GB.json
> +    "addressesTitleBillingAddress": "Billing",
In the german you have shipping address and billing address, in the english you only have shipping and billing. is this intentional?

2025-01-24 13:24 UTC, Bird87ZA commented on src/Storefront/Resources/views/storefront/component/address/address-manager-item.html.twig
> +</li>
new line end of file

2025-01-24 13:24 UTC, Bird87ZA commented on src/Storefront/Resources/views/storefront/component/address/address-manager-modal-create-address.html.twig
> +</div>
same here

2025-01-24 13:24 UTC, Bird87ZA commented on src/Storefront/Resources/views/storefront/component/address/address-manager-modal.html.twig
> +</div>
same here

2025-01-24 13:24 UTC, Bird87ZA commented on src/Storefront/Resources/views/storefront/component/address/addresses-base.html.twig
> +{% endblock %}
same here

2025-01-24 13:24 UTC, Bird87ZA commented on src/Storefront/Resources/views/storefront/page/account/addressbook/address-item.html.twig
> +</li>
same here

2025-01-24 13:24 UTC, Bird87ZA commented on src/Storefront/Resources/views/storefront/page/account/addressbook/address-manager.html.twig
> +{% endblock %}
same here

2025-01-27 07:31 UTC, FlorianKe commented on src/Storefront/Resources/app/storefront/src/plugin/address-manager/address-manager.plugin.js
> +            console.warn(`[AddressManagerPlugin] options.initialTab was expected to be 'billing' or 'shipping', got '${this.options.initialTab}'`);
It's allowed for prod, and should help you debug.

2025-01-27 13:52 UTC, cyl3x approved these changes

2025-01-30 08:19 UTC, mstegmeyer commented
@FlorianKe you have merge conflicts. Could you update your branch? Then we can still merge it this week.

2025-01-31 14:37 UTC, mstegmeyer approved these changes

2025-01-31 15:12 UTC, merged