NEXT-39785 - NEXT-39785 - As a shop customer, I want to get my access back when I forgot my password - email check
shopware/platform pull request #5898
Opened 2024-12-18 10:51 UTC by vanpham-sw

### 1. Why is this change necessary?
Add a separate test case that can check email, this test should be skipped on cloud instance

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).
https://shopware.atlassian.net/browse/NEXT-39785

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

2025-01-03 10:07 UTC, yusufttur requested changes

2025-01-03 10:07 UTC, yusufttur commented on .github/workflows/integration.yml
> +          - "8025:8025"
You shouldn't add mailpit dependecy here. It runs via ats repository.

2025-01-03 10:28 UTC, yusufttur requested changes

2025-01-03 10:28 UTC, yusufttur commented on .github/workflows/integration.yml
> +          - "8025:8025"
add after these as .env variable after line 26:
      MAILER_DSN: "smtp://localhost:1025"
      MAILPIT_BASE_URL: "http://localhost:8025"

2025-01-03 10:29 UTC, yusufttur commented
add after these as .env variable after line 26:
      MAILER_DSN: "smtp://localhost:1025"
      MAILPIT_BASE_URL: "http://localhost:8025"
      See refererence: https://github.com/shopware/SwagCommercial/blob/trunk/.github/workflows/integration.yaml#L54

2025-01-03 12:37 UTC, yusufttur commented on tests/acceptance/tests/Account/ForgotPassword.spec.ts
> +    await test.step('Navigate to the login page and click on forgot password', async () => {
Please leave a blank line between variables and test step.

2025-01-03 12:40 UTC, yusufttur commented on tests/acceptance/tests/Account/ForgotPassword.spec.ts
> +test ('As a customer, I can create and login with new password with existing customer email address.', { tag: '@Account @Password' }, async ({
```suggestion
test ('As a customer, I can reset my password using the password recovery process for an existing account and successfully log in with the new password.', { tag: '@Account @Password' }, async ({
```

2025-01-03 12:43 UTC, yusufttur requested changes
Well done, just need small improvements. 💯

2025-01-06 07:42 UTC, yusufttur approved these changes

2025-01-14 08:24 UTC, philipreinken approved these changes

2025-01-14 09:18 UTC, merged