NEXT-39235 - Make forms accessible
shopware/platform pull request #5901
Opened 2024-12-18 11:44 UTC by Phil23

## Accessible form validation
To make forms more accessible, I overhauled the form handling in the Storefront, which includes local form validation and accesibility best-practices. The changes are implemented behind the `ACCESSIBILITY_TWEAKS` feature flag.

### Implemented best-practices
Sadly, the native browser validation methods are not accessible by default. Therefore, we decided to create custom form handling and disable the native validation of the browser. In the following you can learn more about specific best-practices we implemented for accessible form handling and optimization for screen readers.

#### Form
* The form has the `novalidate` attribute to not use native validation by the browser.
* The `checkValidity()` method of the form is replaced by a custom implementation.

#### Required fields
* The asterisk to mark required fields has now a highlight color for better contrast.
* The asterisk got the `aria-hidden` attribute, because it is irritating to screen readers. The required state is already read out by screen readers if the form field has the necessary attributes.
* Required fields are not marked with a `required` attribute, but with a `aria-required` attribute. This marks the field as required from a semantic standpoint and will be read out by screen readers, but will not trigger native validation.

#### Input validation
* Fields are validated by a local form validation on direct change, but only if changed. The `input` event is used instead of the `change` or `blur` event because these fire everytime and not on immediate change. It is a common pattern that keyboard users tab through a form to get a sense of available fields without filling them out. Therefore, the fields should only be validated on change and then with immediate feedback. If the feedback happens only on `blur` event, it can be irritating because the user has already moved on to the next field.
* Local field validation is implemented with a custom JavaScrpt plugin and can be configured via the `data-validation` attribute. You can pass a comma separated list of validation rules the field should be checked against. You can define the priority of these validators by their order. The first validator has the highest priority. This is important to always give the user the right validation feedback. Only the validation message with the highest applying validator is shown to the user and read out by screen readers.

#### Input feedback
* Every field has a feedback area beneath it that is referenced with the `aria-describedby` attribute. It is used to show a validation message to users, which is also read out by screen readers.
* Optionally every input field can have a description area beneath it to give more context to the user. If present, the description is also referenced via the `aria-describedby` attribute and read out by screen readers.
* Besides the normal color feedback, invalid fields now also display an error icon on the right side of the input. This is an important visual feedback for users which find it difficult to identify colors.
* Placeholder labels were removed from most form fields, as they are irritating and don't add value, especially if they just mirror the content of the label.

#### Form validation
* Besides the immediate field validation feedback, all fields will be validated when submitting the form. 
* If there are still invalid fields, they will be highlighted with the necessary visual feedback.
* In addition, the page will focus the first invalid field. The browser will automatically scroll the page to that field if it is not in view.

### Before:  
![form_validation_before](https://github.com/user-attachments/assets/0ce1c28b-2640-4d58-8c7c-91206af0d370)

### After:
![accessible_form_validation](https://github.com/user-attachments/assets/e59b8095-35a5-4503-98a9-daf5135fb5a1)

### Testing
All standard forms in the Storefront have been updated to the new handling. The changes are still behind the feature flag `ACCESSIBILITY_TWEAKS`. The testing should include all forms to check them for the described best practices and proper functionality. The form handler plugin and the validation service are covered by unit and integration style tests. In addition, the existing acceptance tests for the registration were adjusted.

**Forms affected by the change:**  
* Login
* Guest Login
* Registration
* Custom Registration
* Customer profile
* Change email
* Change password
* Recover password
* Reset password
* Address creation
* Address editing
* Product reviews
* Newsletter registration (CMS)
* Contact form (CMS)

2024-12-18 11:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=5901) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=5901) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=5901) it.</sub>

2024-12-20 10:00 UTC, BrocksiNet commented on src/Storefront/Resources/app/storefront/src/plugin/forms/form-handler.plugin.js
> +            throw Error('Element is not of type <form>');
```suggestion
            throw new Error('Element is not of type <form>');
```
Is new missing here?

2024-12-20 10:22 UTC, BrocksiNet commented on src/Storefront/Resources/app/storefront/src/plugin/forms/form-handler.plugin.js
> +        return invalidFields.length <= 0;
```suggestion
        return invalidFields.length === 0;
```

2024-12-31 10:43 UTC, tobiasberge reviewed
@Phil23 I tested the changes with and without feature toggle. 

Looks really good with activated flag, the forms look much cleaner without all the placeholders and better `*` and the error handling works. 👍 

I found one thing using reCAPTCHA. With the old form handling, I was unable to submit the form via the submit button when the captcha was invalid/not filled. And the reCAPTCHA iframe gets a red outline. (`.grecaptcha-v2-container iframe.has-error`).

With the new form handling `ACCESSIBILITY_TWEAKS=1` I seem to get the hard server error instead and the submit is not prevented. (Tested a few times using Chrome)

**Old form handling**

![image](https://github.com/user-attachments/assets/a7fd1754-13b2-45c9-9845-14aa528cb8d8)

**New form handling**

![image](https://github.com/user-attachments/assets/8c0aa12a-d283-45c1-a07b-5d13d87fcb25)

![image](https://github.com/user-attachments/assets/7ffd2e22-d778-4df3-8ffc-d9bec6bd23e2)

![image](https://github.com/user-attachments/assets/9ccd82c9-3a75-456b-a98f-d94f0121d5f4)

The normal captcha seems to work in general. On initial submit (without filling it), it is not marked as invalid. When I fill out all other fields first and then leave it empty, I get the native form submit and after redirect I receive the error.

**New form handling**

First submit:
![image](https://github.com/user-attachments/assets/aa8ba7c5-64ca-4faa-bf33-cd8903ae3eeb)

After filling all other fields and submit:
![image](https://github.com/user-attachments/assets/12dcd6ed-4ea1-4eba-b152-148497fde50e)

**Old form handling**

The old form handling seemed to consider the field in the local validation and it was marked as invalid right away:

![image](https://github.com/user-attachments/assets/e7d45414-183a-44c4-bca7-b344373e8693)

One nit pick: The `*` of the captcha is not red as the other required fields. 

Regarding accessibility I guess this kind of captcha is problematic in general. It seems like reCAPTCHA considers this and offers an audio alternative. But I haven't tested it yet using the screen reader. Personally, for the scope I would look at the captcha issues in a follow-up task and only fix the form submit.

https://friendlycaptcha.com/insights/captcha-accessibility/

2024-12-31 10:43 UTC, tobiasberge commented on src/Storefront/Resources/app/storefront/src/helper/form-validation.helper.js
> +     * @param {function} validationFunction - They function that does the validation of the field value.
```suggestion
     * @param {function} validationFunction - The function that does the validation of the field value.
```

2024-12-31 10:43 UTC, tobiasberge commented on src/Storefront/Resources/app/storefront/src/main.js
>  PluginManager.register('FormValidation', () => import('src/plugin/forms/form-validation.plugin'), '[data-form-validation]');
We should also add deprecation messages in the files `form-validation.plugin.js` and `form-submit-loader.plugin.js`. The scroll-to-invalid-field seems to already have it.

2024-12-31 10:43 UTC, tobiasberge commented on src/Storefront/Resources/app/storefront/src/plugin/forms/form-handler.plugin.js
> +                if (this.options.focusInvalidField === true) {
Could we use more early returns here instead of 3 nested if conditions?

2024-12-31 10:43 UTC, tobiasberge commented on src/Storefront/Resources/app/storefront/src/plugin/forms/form-scroll-to-invalid-field.plugin.js
> + * @deprecated tag:v6.8.0 - Use the form-handler plugin instead.
See other comment, also add to the other deprecated files.

2025-01-02 08:11 UTC, Phil23 commented on src/Storefront/Resources/app/storefront/src/plugin/forms/form-handler.plugin.js
> +                if (this.options.focusInvalidField === true) {
In my opinion, early returns do not make sense here as it is an early return statement in itself. Two of the three conditions are also just the result of checking for the configuration option and do not apply any complex condition logic. I also don't find this too complex because the code logic is not very difficult to understand, and I added additional comments. Every condition just executes 1-2 lines of code. For sure, always happy for better alternatives. If you have any suggestions on how you would improve this, feel free to share.

2025-01-02 08:23 UTC, Phil23 commented on src/Storefront/Resources/app/storefront/src/plugin/forms/form-handler.plugin.js
> +            throw Error('Element is not of type <form>');
Seems to be a copy-paste thing. I changed it to console error because I'm not a big fan of hard errors on the client side anyway.

2025-01-02 08:35 UTC, tobiasberge commented on changelog/_unreleased/2024-12-17-refactor-form-handling.md
> +You can take a look at the reference documentation of the service and the plugin for further information.
I think the helper `form-validation.helper.js` is meant here? Maybe we can tell the file name here again or even provide a one liner example with:

You can add your own validators using: `window.formValidation.addValidator()`

2025-01-02 08:36 UTC, tobiasberge commented on src/Storefront/Resources/views/storefront/element/cms-element-form/form-components/cms-element-form-input.html.twig
> +        {# @deprecated tag:v6.7.0 - Block will be removed. Form field is replaced by a central component. #}
```suggestion
        {# @deprecated tag:v6.7.0 - Block will be removed. Form field is replaced by a central component `component/form/form-input.html.twig`. #}
```

2025-01-02 08:36 UTC, tobiasberge commented on src/Storefront/Resources/views/storefront/element/cms-element-form/form-components/cms-element-form-input.html.twig
> +        {# @deprecated tag:v6.7.0 - Block will be removed. Form field is replaced by a central component. #}
```suggestion
        {# @deprecated tag:v6.7.0 - Block will be removed. Form field is replaced by a central component `component/form/form-input.html.twig`. #}
```

2025-01-02 08:40 UTC, tobiasberge commented on src/Storefront/Resources/views/storefront/page/account/profile/recover-password.html.twig
> +                              {% if feature('ACCESSIBILITY_TWEAKS') %}data-form-handler="true"{% endif %}
Could we also do this as if-else instead of multiple checks?

```twig
<form
  action="{{ path('frontend.account.recover.request') }}"
  {# @deprecated tag:v6.7.0 - Form validation plugin will be replaced by form handler plugin. #}
  {% if feature('ACCESSIBILITY_TWEAKS') %}
    data-form-handler="true"
  {% else %}
    data-form-validation="true"
    data-form-submit-loader="true"
  {% endif %}>
```

2025-01-02 09:10 UTC, tobiasberge commented on src/Storefront/Resources/views/storefront/utilities/form-validation-config.html.twig
> +    window.validationMessages = {
Is this supposed to be extended by other developers who want to add another validator and error message? What would be the way to go here? The default validators are using the `window.validationMessages`. Right now I have to override/copy the default messages? Or maybe I overlooked something in the Upgrade notes / docs.

```twig
{% sw_extends '@Storefront/storefront/utilities/form-validation-config.html.twig' %}

{% block form_validation_config %}
<script>
    window.validationMessages = {
        'required': '{{ "error.VIOLATION::IS_BLANK_ERROR"|trans|sw_sanitize }}',
        'email': '{{ "error.VIOLATION::INVALID_EMAIL_FORMAT_ERROR"|trans|sw_sanitize }}',
        'confirmation': '{{ "error.VIOLATION::NOT_EQUAL_ERROR"|trans|sw_sanitize }}',
        'minLength': '{{ "error.VIOLATION::TOO_SHORT_ERROR"|trans|sw_sanitize }}',
        'iban': '{{ "error.VIOLATION::IBAN_ERROR"|trans|sw_sanitize }}',
    };
</script>
{% endblock %}
```

```js
window.formValidation.addValidator('iban'), () => {}, window.validationMessages['iban'])
```

If someone is supposed to extend this here maybe we can offer a variable as API for extension:

```twig
{% set validationMessages = {
    required: "error.VIOLATION::IS_BLANK_ERROR"|trans|sw_sanitize,
    email: "error.VIOLATION::INVALID_EMAIL_FORMAT_ERROR"|trans|sw_sanitize,
    confirmation: "error.VIOLATION::NOT_EQUAL_ERROR"|trans|sw_sanitize,
    minLength: "error.VIOLATION::TOO_SHORT_ERROR"|trans|sw_sanitize,
} %}

{% block form_validation_config %}
    <script>
        window.validationMessages = {{ validationMessages|json_encode|raw }};
    </script>
{% endblock %}
```

And then in the extension:

```twig
{% sw_extends '@Storefront/storefront/utilities/form-validation-config.html.twig' %}

{% block form_validation_config %}
    {% set validationMessages = validationMessages|merge({
        iban: "error.VIOLATION::IBAN_ERROR"|trans|sw_sanitize,
    }) %}

    {{ parent() }}
{% endblock %}
```

2025-01-02 09:16 UTC, tobiasberge commented on src/Storefront/Resources/app/storefront/src/plugin/forms/form-handler.plugin.js
> +            throw Error('Element is not of type <form>');
I would also prefer this or `console.error` over a hard error. 👍

2025-01-07 14:22 UTC, Phil23 commented on src/Storefront/Resources/views/storefront/utilities/form-validation-config.html.twig
> +    window.validationMessages = {
It is already simply possible. There are two ways to add or overwrite error messages.

Either pass them together with a custom validator:
```JavaScript
window.formValidation.addValidator('test', () => false, 'Field is not valid');
```

Or simply add or overwrite an error message:
```JavaScript
window.formValidation.addErrorMessage('test', 'Field is not valid');
```

2025-01-07 14:49 UTC, Phil23 commented on changelog/_unreleased/2024-12-17-refactor-form-handling.md
> +You can take a look at the reference documentation of the service and the plugin for further information.
I added some additional information.

2025-01-07 14:58 UTC, Phil23 commented
@tobiasberge thanks for testing. 👍 

I added compatibility for the Basic Captcha, Google reCaptcha V2, and Google reCaptcha V3. 

Feel free to take a look.

2025-01-07 15:00 UTC, tobiasberge commented on src/Storefront/Resources/views/storefront/utilities/form-validation-config.html.twig
> +    window.validationMessages = {
Yes, but where does my translated error message come from? For example:

```js
window.formValidation.addErrorMessage('test', 'The IBAN is not valid');
                                               ^^^^^^^^^^^^^^^^^^^^^^
```
This is hard-coded english. And the core error messages use the symfony translations from `window.validationMessages`. And I was wondering how I am supposed to translate the message. Should I extend the window and use it from there? Like `window.formValidation.addErrorMessage('test', window.validationMessages.myCustomMessage);`

2025-01-08 10:43 UTC, yusufttur commented
Since this is not an input field, we can improve error handling for privacy checkbox a bit: 
`Confirm you’ve read and accepted the terms to proceed.`
![Screen Shot 2025-01-08 at 11 42 04 AM](https://github.com/user-attachments/assets/0a842c4b-cf66-4080-acce-55b49b2b8968)

2025-01-08 13:36 UTC, yusufttur reviewed
Since this is not an input type text-field, we can improve error handling for privacy checkbox a bit:
`Confirm you’ve read and accepted the terms to proceed.`
![Screen Shot 2025-01-08 at 11 42 04 AM](https://github.com/user-attachments/assets/d75e05b0-9c85-4e5b-8bfb-48e63a8ad696)

2025-01-10 11:17 UTC, Phil23 commented
@tobiasberge I added a corresponding PR in Commercial for adding compatibility for the Friendly Captcha.

https://github.com/shopware/SwagCommercial/pull/63

2025-01-19 15:12 UTC, tobiasberge approved these changes

2025-01-20 14:52 UTC, yusufttur approved these changes

2025-01-20 15:18 UTC, mitelg requested changes

2025-01-20 15:18 UTC, mitelg commented on composer.json
> +        "shopware/commercial": "6.9.0",
needs to be reverted!

2025-01-20 15:29 UTC, Phil23 commented on composer.json
> +        "shopware/commercial": "6.9.0",
Oh damn, that is so annoying. Accidentally committed while resolving merge conflicts.

2025-01-20 15:32 UTC, Phil23 commented on composer.json
> +        "shopware/commercial": "6.9.0",
Fixed

2025-01-21 08:21 UTC, mitelg approved these changes

2025-01-21 15:05 UTC, merged

2025-04-28 10:42 UTC, aragon999 commented
One question regarding the removal of the placeholders:

The placeholders have been removed on the register form, but not on the contact form:
> Placeholder labels were removed from most form fields, as they are irritating and don't add value, especially if they just mirror the content of the label.

Was this on purpose, or was this simply missed when implementing it. From what I understand they should also be removed (https://github.com/shopware/shopware/blob/v6.6.10.3/src/Storefront/Resources/views/storefront/element/cms-element-form/form-types/contact-form.html.twig#L30-L31)