NEXT-40062 - [A11y] Offer HTML alternative to our pdf standard documents
shopware/platform pull request #5911
Opened 2024-12-19 04:59 UTC by silverDuy

### 1. Why is this change necessary?

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

2024-12-19 04:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=5911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=5911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=5911) it.</sub>

2024-12-20 01:21 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +4. **Email Attachments**:
For the last discussion, we'll go with injecting URL to customer access instead of an attachment file, due  many email provider not allow HTML file

2024-12-20 01:57 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +        [
Could we simply pseudo-code here? We just show what is most code impacted: In my opinion, an ADR doesn't need to have detailed coding. 

Ex: 
public function render(array $operations, Context $context, DocumentRendererConfig $rendererConfig): RendererResult
{
    ...
    $html = $this->documentTemplateRenderer->render(..) << that helps me quickly not need to check do we have different constructor parameters or not

2024-12-20 02:14 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* In class `Shopware\Core\Checkout\Document\Controller\DocumentController` we will update method `downloadDocument` (`'/api/_action/document/{documentId}/{deepLinkCode}'`) to get a new query paramete
The route and controller are not very interesting. May we add a section on how we protect HTML files and store all those files?

2024-12-20 06:04 UTC, nguyenytran approved these changes

2025-01-02 09:29 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +4. **Email Attachments**:
How can the customer then "download" e.g. his HTML invoice? I guess it's important that these documents can be persisted by the customer. That's why PDF attachments are great, as they are stored inside the email and can be saved to another more persistent location if needed.

A download URL isn't great, because what if that URL isn't working anymore (e.g. Shop domain changed, Shop doesn't exist anymore, ...), but I guess is fine? At least I remember that I received some invoices via download links in my personal life.

Also what is meant by "go with injecting URL to customer access"? Will that URL render HTML in the browser or trigger a download of a `*.html` file?

2025-01-02 09:43 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* The deep link code to open HTML documents will be used to authenticate the user and ensure that the user has access to the document.
I guess you could reuse the same logic as for downloading PDF documents? But I have another thing in my mind that is missing here:

As you are dealing with HTML, which potentially can contain malicious code, the worst case scenario would be in my opinion:
- user clicks link to view HTML document
- browser opens and renders html under the shops domain
- JS code executes under the shops domain name
- We basically enabled [cross site scripting](https://en.wikipedia.org/wiki/Cross-site_scripting)

That's why I would strongly recommend only dealing with files (`*.pdf` or `*.html`) in a way that only allows to download them. The user can then open the locally stored `*.html` in a browser to view it.

2025-01-07 08:56 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* The deep link code to open HTML documents will be used to authenticate the user and ensure that the user has access to the document.
Hi @MalteJanz 

Thank your feedback. After discussing with Juri and Tim, we have an idea to go in the same direction as you suggested:

For email, we will send a new email along with the original email with the content clearly explained and in the directions:

FIY:

```
"Dear {customer.first_name}{customer.last_name},

A new document has been added to your order {OrderNumber}. You should have received the original document in a separate mail.

For better accessibility, we also provide an HTML version of this document here: {Link to HTML file}

For data protection reasons, the HTML version requires a login.

In case of a guest order, you can use your mail address and postal code of the billing address."
```

As you said, when the user clicks on the link, it will lead to the shop. From here, the user can view or download the content.

2025-01-07 08:57 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +4. **Email Attachments**:
Hi @MalteJanz , thank your feedback. I already update more details about that in the following thread below.

2025-01-07 13:05 UTC, keulinho requested changes

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +In addition to the existing PDF documents generated with DomPDF, we will provide standard document types in an accessible HTML format that fulfills A11y requirements.
Let's add some thoughts on why we are doing that, in general ADRs should not only state what we are doing, but why we decided to do so

some things I would expect here:
HTML is by design already structured and better suited for a11y than tagged pdfs
Support for generating tagged pdfs is low, currently no PHP lib supports it
SOme institutions are already moving from PDF to HTML for A11y reasons

Maybe @ravenokko can add some thoughts here especially also on the last point

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +    - **Flow Builder**: Automatically generates both PDF and HTML documents.
Will there be an option to say you only want one or the other? 
Whatever the answer, please mention here and if possible also why we do it that way

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* HTML documents will be generated using the same templates as PDF documents.
Based on the test to open our current templates generated HTML in the browser it looked quite ugly, probably this means that the existing templates need to be adjusted (not just our default templates, but the custom templates as well right)?
If that assumption is correct, can we:
1. document what needs to change in the templates based on what we needed to for our default templates?
2. built a way to opt-in that a given template is ready to be generated over HTML?

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +  - We will modify the document entity to store media IDs for both PDF and HTML documents:
what happens to the existing `documentMediaFileId`? Will we deprecate and remove it? 

As long as the existing Field is there it will always point to the pdf document right? So let's mention that as well

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* HTML documents will be stored as media files, the same way we store PDF files.
Is there some way to "fingerprint" the generation date of the HTML into the file? To make sure that the HTML was not generated at runtime (and thus possibly changed after the fact)? As that is the main benefit of using PDFs 

IIRC @ravenokko  mentioned that there are some ways to do that with HTML files during our call 🤔

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +In addition to the existing PDF documents generated with DomPDF, we will provide standard document types in an accessible HTML format that fulfills A11y requirements.
We don't necessarily need this in the ADR, but at least when we release it, I think it would be helpful to have a comparison between the formats what are the pros and cons, e.g. regarding a11y, but also: client support, e-invoice support, "trust" etc -> probably more for PM side

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* Added new generic method `loadHtmlA11y` to support rendering HTML a11y documents in `AbstractDocumentRenderer`:
* what does `generic` mean here? Will it be abstract or not? 
* `loadHtmlA11y` -> I would drop the A11y suffix everywhere, `$renderer->loadHtml()` or `$doc->setHtml()` is more readable and clear enough IMHO

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* Update the render method in all classes extending `AbstractDocumentRenderer` to set the html a11y content in the document entity:
What happens if e.g. for custom renderer (as our system is generic here) that does not happen right away? I assume that the HTML for the time being is nullable and we handle it gracefully if it is not yet set?

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* Update the render method in all classes extending `AbstractDocumentRenderer` to set the html a11y content in the document entity:
And can we also add this point to the `Breaking changes` section with the changes needed to the templates itself?

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* The deep link code to open HTML documents will be used to authenticate the user and ensure that the user has access to the document.
Is there a reason why we not add the HTML as a second attachment in the original mail?

I would expect if a document is also generated as HTML to have an option to add that as well as attachment in this dialogue: 
![Screenshot 2025-01-07 at 14 01 37](https://github.com/user-attachments/assets/f8171732-58df-4e83-92d5-6061fb4bb1a3)

2025-01-07 13:05 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* The deep link code to open HTML documents will be used to authenticate the user and ensure that the user has access to the document.
We can additionally provide the link to the HTML inside the email template variables, so it can be used there as well, but not sure if we should add another email flow by default for this

2025-01-07 13:14 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* Update the render method in all classes extending `AbstractDocumentRenderer` to set the html a11y content in the document entity:
looking at the implementation, i have questions if this is the right place to put the rendering of the HTML, why don't we do it on the level of the `\Shopware\Core\Checkout\Document\Service\DocumentGenerator`, similar to how we access the `PdfRenderer`? 

That way we don't need to adjust the all the abstract renderers 🤔

2025-01-07 13:31 UTC, keulinho commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* Update the render method in all classes extending `AbstractDocumentRenderer` to set the html a11y content in the document entity:
wouldn't it be cleaner to deprecate rendering of the HTML in the abstract renderers:
```
                $html = $this->documentTemplateRenderer->render(
                    $template,
                    [
                        'order' => $order,
                        'config' => $config,
                        'rootDir' => $this->rootDir,
                        'context' => $context,
                    ],
                    $context,
                    $order->getSalesChannelId(),
                    $order->getLanguageId(),
                    $locale->getCode()
                    $locale->getCode(),
                );
 ```
 
 And instead only provide the template options:
 ```
                 $doc->setTemplateOptions([
                    $template,
                    [
                        'order' => $order,
                        'config' => $config,
                        'rootDir' => $this->rootDir,
                        'context' => $context,
                    ],
                    $context,
                    $order->getSalesChannelId(),
                    $order->getLanguageId(),
                    $locale->getCode(),
                ]);
```

Then the pdf renderer is responsible of first generating the HTML for the pdf and the HTML renderer is responsible of directly generating the "finished" HTML?

2025-01-07 16:30 UTC, ravenokko commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* HTML documents will be stored as media files, the same way we store PDF files.
+1 on some sort of timestamp (either in the file, or file metadata) - the tricky thing we need to address is versioning, which isn't an a11y issue so much as a trust/legal issue. PDF's have high trust value because they are viewed as concrete and unchanging, while HTML by design is dynamic. So we do need to clarify how/when these files are generated in addition to being stored, so customers can trust that they won't be changed.

But perhaps we can also emphasize that, since we are still also providing the pdf's, customers can see they will match.

2025-01-08 11:32 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* The deep link code to open HTML documents will be used to authenticate the user and ensure that the user has access to the document.
Many email systems block HTML file attachments because of virus scanners, so we can't attach them directly.

The first idea was to add a link to the HTML file in existing emails, like the Order Confirmation:

1. However, we can’t be sure, in all cases, that the documents actually already exist when the mail (e.g. Order Confirmation) has been sent. 
2. We also considered injecting this content using a migration default email template, which could be more complicated and confuse customers about the default templates. 

Therefore, Juri and Tim suggest we probably need a new mail template that contains the HTML document link. Customers can access the HTML version of the documents through this link. The email should clearly explain the purpose and provide an understandable reason for this approach.

Additionally, we can provide an option setting for this feature in the Document Settings.

Does this work for you, too?

2025-01-08 12:06 UTC, nguyenytran commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* Update the render method in all classes extending `AbstractDocumentRenderer` to set the html a11y content in the document entity:
Hi @keulinho, We need two different configs for the renderer template. That's why I need to move the renderer template into the abstract renderers
- with HtmlRenderer, we need to override the config like

<img width="871" alt="Screenshot 2025-01-08 at 19 05 17" src="https://github.com/user-attachments/assets/9d3c70e0-6bdd-458b-988f-f717398971e0" />

2025-01-08 12:38 UTC, ravenokko commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +In addition to the existing PDF documents generated with DomPDF, we will provide standard document types in an accessible HTML format that fulfills A11y requirements.
> SOme institutions are already moving from PDF to HTML for A11y reasons
> Maybe @ravenokko can add some thoughts here especially also on the last point

The most prominent examples are government websites which were required to meet these accessibility requirements ala the BITV 1.0 since the early 2000's. While PDF's haven't completely gone away, you can see most gov websites have shifted the overwhelming majority of their content to HTML.

2025-01-08 16:10 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* The deep link code to open HTML documents will be used to authenticate the user and ensure that the user has access to the document.
I would also vote against introducing a completely new email + template just for sending the a11y link to the customer, as mentioned here: https://github.com/shopware/shopware/pull/5834#discussion_r1907324177

If we can't override existing templates, because they might got adjusted by the merchant already, we should think about other solutions to make them properly upgrade with the shopware major (see linked comment above for one idea).

In the end this decision and the reasoning behind it should also be documented in this ADR

2025-01-08 16:26 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* HTML documents will be stored as media files, the same way we store PDF files.
+1 at the very least we should have a meta tag in the HTML head with the generation timestamp. As I personally have never received an Invoice as HTML, I would be interested in how other providers deal with this problem, as HTML is easy to modify (in contrast to PDF).

Only crazy idea that would come to my mind to use some kind of cryptography (checksum / signing) system that validates itself when the document is opened (by executing a little Javascript) and warns the reader that this document was tempered with / isn't signed by the original author anymore. Basically like you can verify that a [JWT token](https://en.wikipedia.org/wiki/JSON_Web_Token) wasn't modified, with some kind of digital signature

2025-01-09 04:46 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* HTML documents will be stored as media files, the same way we store PDF files.
Thank your feedback,

As suggested, we will add a metadata header to ensure that HTML is not generated at runtime. We will also add some rule Content-Security-Policy meta-tag to reduce the risk of XSS attacks (such as not allowing js, trusted domain)

And during our refinement meeting, it was mentioned that "HTML files don't legally need to be immutable as long as a PDF fulfilling all requirements is provided."

Regarding adding a logic signature check: 
IMHO, it might introduce additional complexity, such as managing keys, storing hashes, and verifying performance with many Document files. Moreover, using JavaScript for this purpose could be risky; it could not be allowed or disabled.

May we simply benefit from HTTPS encryption, which ensures that all data is transmitted securely and the content remains during transmission?

2025-01-10 14:08 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* HTML documents will be stored as media files, the same way we store PDF files.
> As suggested, we will add a metadata header to ensure that HTML is not generated at runtime.

Thanks, but technically it could still be "generated at runtime" right?😂 But at least the user could download the file and later kind of proof, that it was generated in the past, and they could find out if the document behind the download link got further modified later, e.g. on accident with a bug in our implementation. For that they of course need to inspect the HTML meta tag.

> And during our refinement meeting, it was mentioned that "HTML files don't legally need to be immutable as long as a PDF fulfilling all requirements is provided."

That's good to know. Then I don't think we need to care about that and don't have to introduce anything like it.

> May we simply benefit from HTTPS encryption, which ensures that all data is transmitted securely and the content remains during transmission?

Yes, but I think HTTPS should already be a given at this point in time and every shop should have it set up. So nothing really to consider for the implementation, if that was a question?

2025-01-14 08:53 UTC, ravenokko commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* HTML documents will be stored as media files, the same way we store PDF files.
For examples: 

- Payment providers like PayPal/Stripe email links to webpages (if you have a paypal account you can send yourself invoices)
- App Stores email the invoice itself and link to the account
- A lot of the major platforms (Microsoft, Google, Amazon, etc.) will also email a summary with a link to the customer account for things like Azure/Google Cloud/etc.

2025-01-17 04:35 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* The deep link code to open HTML documents will be used to authenticate the user and ensure that the user has access to the document.
After discussion, I have updated the following feedback and section email Delivery and Email Migration.

I would resolved that thread. Feel free open it again if you have any other feedback

2025-01-17 04:36 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +* HTML documents will be stored as media files, the same way we store PDF files.
After discussion, I have updated the following feedback and section Metadata and Security:

I would resolve that thread. Feel free to open it again if you have any other feedback

2025-01-17 04:40 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +    - **Flow Builder**: Automatically generates both PDF and HTML documents.
I have updated the section Flow Builder

This setup requires no additional special actions, and merchants can customize file generation for "Generate documents" in the Document Settings

2025-01-17 04:42 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +In addition to the existing PDF documents generated with DomPDF, we will provide standard document types in an accessible HTML format that fulfills A11y requirements.
I have updated the following feedback in the section Decision:

I would resolve that thread. Feel free to open it again if you have any other feedback

2025-01-20 08:50 UTC, MalteJanz approved these changes
Just suggested some wording changes, otherwise the ADR LGTM 👍

2025-01-20 08:50 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +We have decided to switch from tagged PDFs to HTML for better accessibility.
I wouldn't call it `switch`, as that sounds like we are replacing PDFs. Also we don't have tagged PDFs currently.
```suggestion
We have decided to make HTML documents available in addition to PDF documents, as these are more accessible.
```

2025-01-20 08:50 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +- **Lack of Support**: As current PDFs lack support for accessibility. Few tools, especially in PHP, can create accessible tagged PDFs, making it difficult to maintain PDF accessibility.
```suggestion
- **Lack of Support**: As our current PDFs lack support for accessibility. Few tools, especially in PHP, can create accessible tagged PDFs, making it difficult to maintain PDF accessibility.
```

2025-01-20 08:50 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +Switching to HTML aligns with these trends and ensures we are using best practices for accessibility.
```suggestion
Providing HTML documents aligns with these trends and ensures we are using best practices for accessibility.
```

2025-01-20 08:50 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +    - Support includes `invoice`, `delivery note`, `credit note`, and `cancellation invoice`.
```suggestion
    - Support includes all document types Shopware provides by default, `invoice`, `delivery note`, `credit note`, and `cancellation invoice`. Extensions must adapt themselves.
```

2025-01-20 08:50 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +    - As we can’t attach the HTML file directly due to issues with "virus scanners," many email providers do not allow HTML file attachments.
```suggestion
    - We can’t attach the HTML file directly due to issues with "virus scanners", as many email providers do not allow HTML file attachments. Instead we will provide a link inside the Email.
```

2025-01-20 08:50 UTC, MalteJanz commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +    - We will introduce an abstract class, `src/Core/Checkout/Document/Service/AbstractDocumentTypeRenderer`, to support rendering multiple document types, including `PDF`, `HTML`, and `XML`.
Do we already support `XML`? Otherwise I would remove that as an example

2025-01-21 02:02 UTC, nam4am commented on adr/2024-12-19-offer-html-alternative-to-our-pdf-standard-document.md
> +    - We will introduce an abstract class, `src/Core/Checkout/Document/Service/AbstractDocumentTypeRenderer`, to support rendering multiple document types, including `PDF`, `HTML`, and `XML`.
```suggestion
    - We will introduce an abstract class, `src/Core/Checkout/Document/Service/AbstractDocumentTypeRenderer`, to support rendering multiple document types, including `PDF` and `HTML`.
```

2025-01-23 09:43 UTC, keulinho approved these changes

2025-01-23 10:52 UTC, merged