feat(pinia migration): migrate swPromotionDetail store to pinia
shopware/platform pull request #5921
Opened 2024-12-19 11:50 UTC by tajespasarela

NEXT-39906

2025-01-02 09:45 UTC, seggewiss requested changes

2025-01-02 09:45 UTC, seggewiss commented on src/Administration/Resources/app/administration/src/module/sw-promotion-v2/page/sw-promotion-v2-detail/store.ts
> +    //
This comment can be removed right? 😊

2025-01-02 12:26 UTC, tajespasarela commented on src/Administration/Resources/app/administration/src/module/sw-promotion-v2/page/sw-promotion-v2-detail/store.ts
> +    //
done

2025-01-07 07:49 UTC, jleifeld approved these changes

2025-01-07 12:15 UTC, seggewiss approved these changes

2025-01-07 12:15 UTC, merged