test: skip test
shopware/platform pull request #5938
Opened 2024-12-20 10:06 UTC by vanpham-sw

### 1. Why is this change necessary?

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

2024-12-20 12:17 UTC, patzick requested changes
Hey!
- pr description is missing for context, reviewer needs to find it from the code
- I'd not bypass linter rules, better to work with them (see code suggestion)
- dependencies bump (and lockfile changes) should be a separate PR to avoid conflicts

Conditional skip rule is added here: https://github.com/shopware/shopware/pull/5931/files#diff-e54f782f884d325fa4b4185de6674df3486ddc72e109791692b90f213ec91ba8R19 in #5931 so can be used after the merge

2024-12-20 12:17 UTC, patzick commented on tests/acceptance/package.json
> +    "@shopware-ag/acceptance-test-suite": "^11.1.0",
this should not be a part of this PR, dependencies bump should be a separate PR

2024-12-20 12:17 UTC, patzick commented on tests/acceptance/tests/Accessibility/StorefrontAccessibility.spec.ts
> +    }
linter rules exist to not be omitted :)

```suggestion
    test.skip(InstanceMeta.features['V6_7_0_0'], 'This test is incompatible with V6_7_0_0');
```

2024-12-20 21:31 UTC, frobel commented on tests/acceptance/tests/Account/CustomerRegistration.spec.ts
> +    }
Not necessary to skip that test. It **was** a caching problem and it is solved now. (Please double-check with last nightly build)

2024-12-23 13:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=5938) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=5938) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: vanpham-sw<br/>:white_check_mark: ocavli<br/>:x: yusufttur<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=5938) it.</sub>

2024-12-23 13:36 UTC, patzick approved these changes
Much cleaner 🙌

2024-12-24 08:00 UTC, pweyck approved these changes

2024-12-24 08:39 UTC, merged