NEXT-39367 - ZUGFeRD renderer
shopware/platform pull request #5951
Opened 2024-12-23 11:19 UTC by En0Ma1259

Create new document type "ZUGFeRD invoice" and "Embedded ZUGFeRD invoice".

<img width="509" alt="image" src="https://github.com/user-attachments/assets/734b167c-1fe2-48a8-9dfa-b5012fab6ea5" />
<img width="976" alt="image" src="https://github.com/user-attachments/assets/5913d9b6-8119-4d0d-946c-2714d1e94600" />

The same number range should be used for e-invoices and PDF invoices. As a result, it is necessary to map the document type from a `document_zugferd_...` to the existing `document_invoice` once in administration.

The current field for the address for the document configuration has been marked as deprecated. New atomic fields have been added that are required for e-invoicing.

Several new events to manipulate the invoice are added (`ZugferdInvoiceItemAddedEvent`, `ZugferdInvoiceGeneratedEvent`).

2024-12-24 17:15 UTC, mstegmeyer requested changes

2024-12-24 17:15 UTC, mstegmeyer commented on composer.json
> +        "horstoeko/zugferd": "1.0.99",
can't we do a `^` here? Don't we want at least bugfixes?

2024-12-24 17:15 UTC, mstegmeyer commented on src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json
> +      "labelDisplayCompanyAddress": "Geschäftsadresse anzeigen (Veraltet v6.7.0)",
"obsolet ab Shopware 6.7"

2024-12-24 17:15 UTC, mstegmeyer commented on src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json
> +      "helpTextCompanyAddress": "Veraltet für 6.7 - Benutze die neuen einzelnen Felder für die Adresse. Verwende Bindestriche (\"-\") um die einzelnen Elemente der Adresse voneinander abzugrenzen. Da
same here: "obsolet ab Shopware 6.7 - ..."

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Renderer/RendererResult.php
> +    protected array $errors = [];
why the change? can't you just use the `addError` / `addSuccess` function?

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Renderer/ZugferdEmbeddedRenderer.php
> +    }
add a deprecated comment directly, so it doesn't get overlooked

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Renderer/ZugferdEmbeddedRenderer.php
> +        $renderResult->assign(['errors' => \array_merge($invoice->getErrors(), $electronicInvoice->getErrors(), $renderResult->getErrors())]);
see above, why not use the `add` functions?

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Renderer/ZugferdEmbeddedRenderer.php
> +                $renderResult->addError($orderId, new \RuntimeException('Electronic invoice is null'));
please no RuntimeException

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Renderer/ZugferdRenderer.php
> +            ]);
no need for an array here, just use `$criteria->addAssociation('lineItems.product.manufacturer');`

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Service/DocumentConfigLoader.php
> +
as phpstan says, you need to use the getters / setters

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Zugferd/ZugferdBuilder.php
> +        $config->__set('isGross',  match ($order->getTaxStatus()) {
can't you just use `setIsGross()`? This is a magic setter and should function this way. Or add setters / getters to the config.

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Zugferd/ZugferdBuilder.php
> +            default => throw DocumentException::generationError('Unsupported tax status'),
Could you check, if the logic in other places is just a `$order->getTaxStatus() === CartPrice::TAX_STATUS_GROSS`? So no exception throwing

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Zugferd/ZugferdBuilder.php
> +        $deliveryDate = $order->getDeliveries()?->first()?->getShippingDateLatest();
Try not to use annotations. Do a quick null-check

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +            'country' => $documentConfig->companyCountry?->getIso(),
please use getters

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +class ZugferdDocument
I find this class to be a very weird mix between a DTO and actual functionality. Is there any reason, why you don't just put these methods as private methods of the ZugferdBuilder?

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +    public function withSellerInformation(DocumentConfiguration $documentConfig): self
the config is already a protected property of the class

2024-12-24 17:15 UTC, mstegmeyer commented on src/Core/Framework/Resources/views/documents/includes/letter_header.html.twig
> +    ]|filter(v => v is not empty and v !== ' ') %}
can we inject this into twig instead of writing it into the template? Maybe also a method of `config`?

2025-01-02 15:17 UTC, En0Ma1259 commented on src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json
> +      "labelDisplayCompanyAddress": "Geschäftsadresse anzeigen (Veraltet v6.7.0)",
Sure? This will still be a valid option. Or do we want to remove the option to hide the address on invoices? And that would be for another ticket then, wouldn't it?

2025-01-03 07:32 UTC, En0Ma1259 commented on src/Core/Checkout/Document/Renderer/RendererResult.php
> +    protected array $errors = [];
Since the class in general is final, this will not have any effect, except to be able to use the `assign` method for `sucess` and `errors`.
With this change, we can assign all errors in one step. Otherwise, we would have multiple `foreach` to add each error separately.

2025-01-06 10:01 UTC, cyl3x commented on src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json
> +      "helpTextCompanyAddress": "Veraltet für 6.7 - Benutze die neuen einzelnen Felder für die Adresse. Verwende Bindestriche (\"-\") um die einzelnen Elemente der Adresse voneinander abzugrenzen. Da
It is also difficult to distinguish between the deprecation and the normal hint. Maybe:
```suggestion
      "helpTextCompanyAddress": "Obsolet ab 6.7. Fülle die Adresse stattdessen in die einzelnen Felder.\n\nVerwende Bindestriche (\"-\") um die einzelnen Elemente der Adresse voneinander abzugrenzen. Das hilft bei der gleichzeitigen Darstellung der Adresse an unterschiedlichen Stellen der Kopfzeile.",
```

2025-01-06 10:01 UTC, cyl3x commented on src/Core/Checkout/Document/DocumentConfiguration.php
> +     * @deprecated tag:v6.7.0 - Will be splitted up into single fields. companyStreet, companyZipcode, companyCity, companyCountry
So everyone understands that this field will be removed:
```suggestion
     * @deprecated tag:v6.7.0 - Will be replaced by single fields: companyStreet, companyZipcode, companyCity, companyCountry
```

2025-01-06 10:01 UTC, cyl3x commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +                $errors[(string) $item->getMessage()][] = $item->getPropertyPath();
Shouldn't it be the other way round, to make it easier to read this array?

2025-01-07 08:11 UTC, En0Ma1259 commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +    public function withSellerInformation(DocumentConfiguration $documentConfig): self
Not any more. Changed it to a `bool` value.

2025-01-07 09:17 UTC, En0Ma1259 commented on composer.json
> +        "horstoeko/zugferd": "1.0.99",
Up until now, everything since 1.0.1 is a bugfix according to the version.
While developing, there were BCs. So I'm not so confident to use a `^`.
So? What should we do?

2025-01-07 09:23 UTC, lernhart commented on src/Core/Checkout/Document/Renderer/RendererResult.php
> +    protected array $errors = [];
We've talked about it this in the past 

Having two `assign` calls is much cleaner, than multiple loops with `add` calls.

2025-01-07 09:27 UTC, lernhart commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +class ZugferdDocument
I find this okay, as this is a mutable DTO, returning itself on the corresponding methods. 

This is signalized by using the `withXYZ` naming approach.

2025-01-07 10:16 UTC, En0Ma1259 commented on src/Core/Checkout/Document/Renderer/ZugferdEmbeddedRenderer.php
> +        $renderResult->assign(['errors' => \array_merge($invoice->getErrors(), $electronicInvoice->getErrors(), $renderResult->getErrors())]);
Will resolve this comment. Whatever we decide on the comment above, I will change this too

2025-01-07 10:21 UTC, mstegmeyer commented on src/Core/Checkout/Document/Renderer/RendererResult.php
> +    protected array $errors = [];
hmm, cleaner yes, but typed no. @En0Ma1259 , please make the call, there is obviously no "the one" way 🤣

2025-01-07 10:22 UTC, mstegmeyer commented on src/Core/Checkout/Document/Renderer/RendererResult.php
> +    protected array $errors = [];
or @Bird87ZA and @cyl3x and @FlorianKe add their opinions ;)

2025-01-07 10:36 UTC, mstegmeyer commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +    }
I had another look here: not every line item has Tax. There is a tax state `free`, where there are never any `CalculatedTax`es. (you can set this e.g. by changing the currency to have a tax free starting price from 0,01.

2025-01-07 10:36 UTC, mstegmeyer commented on src/Core/Checkout/Document/Zugferd/ZugferdBuilder.php
> +            LineItem::PROMOTION_LINE_ITEM_TYPE, LineItem::CREDIT_LINE_ITEM_TYPE => $document->withDiscountItem($lineItem),
There are more line item types, we should be able to handle all, right? There is also `discount` and `custom`. And Container should exist as well, not just the children, right?

2025-01-07 14:34 UTC, FlorianKe commented on src/Core/Checkout/Document/Renderer/RendererResult.php
> +    protected array $errors = [];
Personally I like the `protected` and `assign` more.

2025-01-13 08:47 UTC, En0Ma1259 commented on src/Core/Checkout/Document/Zugferd/ZugferdBuilder.php
> +            LineItem::PROMOTION_LINE_ITEM_TYPE, LineItem::CREDIT_LINE_ITEM_TYPE => $document->withDiscountItem($lineItem),
Added customLineItem. How do I add a `discount` item?

2025-01-14 07:33 UTC, En0Ma1259 commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +    }
Fix it in https://github.com/shopware/shopware/pull/5951/commits/416196228d25dd955f255f77d2a4c9274de36b2b

2025-01-14 07:47 UTC, En0Ma1259 commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +                $errors[(string) $item->getMessage()][] = $item->getPropertyPath();
The error message mapped to fields or the fields mapped to error messages ... honestly, I don't mind. 

I looked over it again. These errors will not be shown anywhere atm. `DocumentException::electronicInvoiceViolation` has the array `$violations` parameter, but will not show up in the response.
How do we add this information into the response? `json_encode` in the message or writing a log entry for this?

2025-01-15 07:04 UTC, cyl3x commented on src/Core/Checkout/Document/Zugferd/ZugferdDocument.php
> +                $errors[(string) $item->getMessage()][] = $item->getPropertyPath();
Normally violations are mapped to fields - as we do this everywhere else in the code, I think it's appropriate to fulfil the expectation that violations are mapped as `property => message(s)`

All parameters should be already available and visible in the response under `meta.parameters` (ref: `ShopwareHttpException::getCommonErrorData`)

2025-01-15 10:03 UTC, Bird87ZA commented on composer.json
> +        "horstoeko/zugferd": "1.0.99",
This is already 4 versions behind. I've asked a question https://github.com/horstoeko/zugferd/issues/231

2025-01-15 10:42 UTC, Bird87ZA approved these changes
LGTM except for the open discussions.

How are we looking on merging this. Are we waiting for @nam4am to merge their A11y changes first, then we move from there? Or what's the plan?

2025-01-15 13:49 UTC, Bird87ZA commented on composer.json
> +        "horstoeko/zugferd": "1.0.99",
it has been answered. I think we can risk using a `^1.0.0` constraint here.

![image](https://github.com/user-attachments/assets/41398fbb-3da5-4fa9-ba2e-84633133012c)

2025-01-16 07:58 UTC, En0Ma1259 commented
> LGTM except for the open discussions.
> 
> How are we looking on merging this. Are we waiting for @nam4am to merge their A11y changes first, then we move from there? Or what's the plan?

I guess we need to. Otherwise, we need to start this branch from his pull request.
Structurewise, we won't need several changes done in this feature branch (e.g. new ZugferdRenderer.php).

2025-01-20 10:33 UTC, mstegmeyer commented on src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json
> +      "labelDisplayCompanyAddress": "Geschäftsadresse anzeigen (Veraltet v6.7.0)",
This confuses me. I understood it this way: we deprecate the "one-line" address and in the future, starting from 6.7, use the line composed from many fields. Is that not correct?

2025-01-20 16:51 UTC, En0Ma1259 commented on src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json
> +      "labelDisplayCompanyAddress": "Geschäftsadresse anzeigen (Veraltet v6.7.0)",
With this option the merchant can toggle, if the address should be shown in the normal invoice (PDF or HTML). So I'm not sure, if we can remove it with 6.7. 

I would suggest a new issue, if we want to get this option removed, but this has nothing to do with e-invoice

2025-01-21 13:09 UTC, Bird87ZA commented on src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json
> +      "labelDisplayCompanyAddress": "Geschäftsadresse anzeigen (Veraltet v6.7.0)",
Yeah I don't think it should be removed. I had a closer look at the code, and the deprecation for the English and German versions are on different fields.

German was on `labelDisplayCompanyAddress` while the English one was on `labelCompanyAddress`. I've fixed it now, and it makes more sense - and fits - now.

2025-02-04 07:14 UTC, En0Ma1259 commented
Will be done with https://github.com/shopware/shopware/pull/6470

2025-02-04 07:14 UTC, closed without merging